# GameSpy Presence & Messaging SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=gptestc

PROG_OBJS = \
	../../../md5c.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsMemory.o\
        ../../../common/gsUdpEngine.o\
	../../../common/macosx/MacOSXCommon.o\
	../../gp.o\
	../../gpi.o\
	../../gpiBuddy.o\
	../../gpiBuffer.o\
	../../gpiCallback.o\
	../../gpiConnect.o\
	../../gpiInfo.o\
        ../../gpiKeys.o\
	../../gpiOperation.o\
	../../gpiPeer.o\
	../../gpiProfile.o\
	../../gpiSearch.o\
	../../gpiUnique.o\
	../../gpiUtility.o\
	../../gpiTransfer.o\
	../gptestc.o\
        ../../../gt2/gt2Auth.o\
        ../../../gt2/gt2Buffer.o\
        ../../../gt2/gt2Callback.o\
        ../../../gt2/gt2Connection.o\
        ../../../gt2/gt2Encode.o\
        ../../../gt2/gt2Filter.o\
        ../../../gt2/gt2Main.o\
        ../../../gt2/gt2Message.o\
        ../../../gt2/gt2Socket.o\
        ../../../gt2/gt2Utility.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
