SHELL       = /bin/sh
GOA         = /usr/local/goa

all:
	cd $(GOA)/Chat/chatc/chatlinux/ ; make clean
	cd $(GOA)/Chat/chatc/chatlinux/ ; make 
	cd $(GOA)/gcdkey/gcdkeylinux/gcdkeyclientlinux ; make clean
	cd $(GOA)/gcdkey/gcdkeylinux/gcdkeyclientlinux ; make 
	cd $(GOA)/gcdkey/gcdkeylinux/gcdkeyserverlinux ; make clean
	cd $(GOA)/gcdkey/gcdkeylinux/gcdkeyserverlinux ; make 
	cd $(GOA)/ghttp/ghttpc/ghttplinux/ ; make clean
	cd $(GOA)/ghttp/ghttpc/ghttplinux/ ; make 
	cd $(GOA)/GP/gptestc/gplinux ; make clean
	cd $(GOA)/GP/gptestc/gplinux ; make 
	cd $(GOA)/gstats/statstest/gstatslinux ; make clean
	cd $(GOA)/gstats/statstest/gstatslinux ; make 
	cd $(GOA)/gstats/persisttest/persistlinux ; make clean
	cd $(GOA)/gstats/persisttest/persistlinux ; make 
	cd $(GOA)/gt2/gt2testc/gt2linux ; make clean
	cd $(GOA)/gt2/gt2testc/gt2linux ; make 
	cd $(GOA)/natneg/simpletest/natneglinux ; make clean
	cd $(GOA)/natneg/simpletest/natneglinux ; make 
	cd $(GOA)/Peer/peerc/peerlinux ; make clean
	cd $(GOA)/Peer/peerc/peerlinux ; make 
	cd $(GOA)/pt/pttestc/ptlinux ; make clean
	cd $(GOA)/pt/pttestc/ptlinux ; make 
	cd $(GOA)/qr2/qr2csample/qr2linux ; make clean
	cd $(GOA)/qr2/qr2csample/qr2linux ; make 
	cd $(GOA)/serverbrowsing/sbctest/sblinux ; make clean
	cd $(GOA)/serverbrowsing/sbctest/sblinux ; make 
	cd $(GOA)/Voice/voicetest/voicetestlinux ; make clean
	cd $(GOA)/Voice/voicetest/voicetestlinux ; make 
	cd $(GOA)/Voice/voicebench/voicebenchlinux ; make clean
	cd $(GOA)/Voice/voicebench/voicebenchlinux ; make 
