#pragma once

enum {
	ID_NEW_AF  = 300,
	ID_AF_LOST,

	ID_AF_TEAM1_ONBASE,
	ID_AF_TEAM2_ONBASE,

	ID_AF_TEAM1_ONBASE_R,
	ID_AF_TEAM2_ONBASE_R,

	ID_AF_TEAM1_ONBASE_ENEMY,	
	ID_AF_TEAM2_ONBASE_ENEMY,

	ID_AF_TEAM1_TAKE,
	ID_AF_TEAM2_TAKE,
	ID_AF_TEAM1_TAKE_R,
	ID_AF_TEAM2_TAKE_R,
	ID_AF_TEAM1_TAKE_ENEMY,	
	ID_AF_TEAM2_TAKE_ENEMY,

	ID_AF_TEAM1_RETURNED,
	ID_AF_TEAM1_RETURNED_R,
	ID_AF_TEAM1_RETURNED_ENEMY,
	ID_AF_TEAM2_RETURNED,
	ID_AF_TEAM2_RETURNED_R,
	ID_AF_TEAM2_RETURNED_ENEMY,


	ID_AH_forcedword		= u32(-1)
};
