//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.11.519.0000
//
//   fxc /nologo /Tps_1_1 /Emain_ps_1_1 /Zpr /Fctest\p11_postprocess.ps
//    postprocess.ps
//
//
// Parameters:
//
//   float4 c_brightness;
//   sampler2D s_base0;
//   sampler2D s_base1;
//   sampler2D s_noise;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   c_brightness c0       1
//   s_base0      s0       1
//   s_base1      s1       1
//   s_noise      s2       1
//

    ps_1_1
    def c1, 0, 0, 0, 1
    tex t0
    tex t1
    tex t2
    add_d2 r0.xyz, t0, t1
    dp3 r1, r0, v1
    mul r1.w, r1.w, 1-v1.w
    mad r0.xyz, r0, v1.w, r1.w
    mul_x2 r1.xyz, t2, r0
    lrp r0.xyz, v0.w, r0, r1
    mad_x2 r0.xyz, r0, v0, c0
  + mov r0.w, c1.w

// approximately 10 instruction slots used (3 texture, 7 arithmetic)
