//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.11.519.0000
//
//   fxc /nologo /Tps_3_0 /Emain_ps_1_1 /Zpr /Fctest\p30_postprocess.ps
//    postprocess.ps
//
//
// Parameters:
//
//   float4 c_brightness;
//   sampler2D s_base0;
//   sampler2D s_base1;
//   sampler2D s_noise;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   c_brightness c0       1
//   s_base0      s0       1
//   s_base1      s1       1
//   s_noise      s2       1
//

    ps_3_0
    def c1, 0.5, 2, 1, 0
    dcl_color_pp v0
    dcl_color1_pp v1
    dcl_texcoord_pp v2.xy
    dcl_texcoord1_pp v3.xy
    dcl_texcoord2_pp v4.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    texld_pp r0, v2, s0
    texld_pp r1, v3, s1
    add_pp r0.xyz, r0, r1
    mul_pp r1.xyz, r0, c1.x
    dp3_pp r0.w, r1, v1
    mad_pp r0.xyz, r0, c1.x, -r0.w
    mad_pp r2.xyz, v1.w, r0, r0.w
    texld_pp r0, v4, s2
    mul_pp r1.xyz, r2, r0
    mad_pp r0.xyz, c1.y, -r1, r2
    add_pp r1.xyz, r1, r1
    mad_pp r0.xyz, v0.w, r0, r1
    mad_pp r0.xyz, r0, v0, c0
    add_pp oC0.xyz, r0, r0
    mov_pp oC0.w, c1.z

// approximately 15 instruction slots used (3 texture, 12 arithmetic)
