//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.06.168.0000
//
//   fxc /nologo /Tvs_2_0 /Emain /Zpr /Fctest\v20_tree_s_dt.vs tree_s_dt.vs
//
//
// Parameters:
//
//   float4 L_hemi_color;
//   float3 L_sun_color;
//   float3 L_sun_dir_w;
//   float4 c_bias;
//   float4 c_scale;
//   float2 c_sun;
//   float4 consts;
//   float4 dt_params;
//   float3 eye_position;
//   float4 fog_plane;
//   row_major float4x4 m_VP;
//   row_major float3x4 m_xform;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   m_VP         c0       4
//   m_xform      c4       3
//   fog_plane    c7       1
//   L_sun_color  c8       1
//   L_sun_dir_w  c9       1
//   L_hemi_color c10      1
//   eye_position c11      1
//   dt_params    c12      1
//   consts       c13      1
//   c_bias       c14      1
//   c_scale      c15      1
//   c_sun        c16      1
//

    vs_2_0
    def c17, 1, 2, -1, 0.5
    def c18, 0.75, 0.25, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    mov r0.w, c17.x
    dp4 r0.x, c4, v0
    dp4 r0.y, c5, v0
    dp4 r0.z, c6, v0
    dp4 oFog, r0, c7
    dp4 oPos.x, c0, r0
    dp4 oPos.y, c1, r0
    mad r2.xyz, c17.y, v1, c17.z
    dp4 oPos.z, c2, r0
    dp3 r1.x, c4, r2
    dp3 r1.y, c5, r2
    dp3 r1.z, c6, r2
    dp4 oPos.w, c3, r0
    dp3 r1.x, r1, -c9
    add r2.xyz, r0, -c11
    mad r0.w, r1.x, c18.x, c18.y
    mul r1.xyz, r0.w, c8
    mov r0, c15
    mad r0, r0, v1.w, c14
    mad r0.xyz, c10, r0.w, r0
    dp3 r2.x, r2, r2
    mad r1.w, v1.w, c16.x, c16.y
    rsq r0.w, r2.x
    mad oD0.xyz, r1, r1.w, r0
    rcp r0.w, r0.w
    mul r0.xy, v2, c13
    mul r0.w, r0.w, c12.w
    mul oT1.xy, r0, c12
    mul r0.w, r0.w, r0.w
    mov oT0.xy, r0
    min r0.w, r0.w, c17.x
    add oD0.w, -r0.w, c17.x
    mul oD1, r0.w, c17.w

// approximately 33 instruction slots used
