# Competition SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=sctest

DEFINES=-D_MACOSX -DGSI_NO_THREADS

PROG_OBJS = \
	../../../md5c.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../common/gsAssert.o\
	../../../common/gsAvailable.o\
	../../../common/gsCore.o\
	../../../common/gsDebug.o\
	../../../common/gsCrypt.o\
	../../../common/gsLargeInt.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsMemory.o\
	../../../common/gsXML.o\
	../../../common/gsSHA1.o\
	../../../common/gsRC4.o\
	../../../common/gsSSL.o\
	../../../common/gsSoap.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../ghttp/ghttpBuffer.o\
	../../../ghttp/ghttpCallbacks.o\
	../../../ghttp/ghttpConnection.o\
	../../../ghttp/ghttpEncryption.o\
	../../../ghttp/ghttpMain.o\
	../../../ghttp/ghttpProcess.o\
	../../../ghttp/ghttpCommon.o\
	../../../ghttp/ghttpPost.o\
	../../../webservices/AuthService.o\
	../../sciInterface.o\
	../../sciMain.o\
	../../sciReport.o\
	../../sciSerialize.o\
	../../sciWebServices.o\
	../sctest.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
