version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true

image:
- Visual Studio 2022

configuration:
- Debug
- Mixed
- Release
- ReleaseMasterGold

platform:
- x64

branches:
  except:
    - dependabot/*

for:
-
  before_build:
    - git submodule update --init --recursive

  build_script:
    - cmd: >
        bash -c "./cmake-initial-configure $CONFIGURATION --vs && ./cmake-build"

  after_build:
    - cmd: >
        bash -c "cd cmake_builds/vs_$(echo $CONFIGURATION | tr '[:upper:]' '[:lower:]') && cpack -B artifacts -C $CONFIGURATION -DCPACK_THREADS=4"

  artifacts:
    - path: cmake_builds/vs_*/artifacts/openxray*.*
      name: openxray

test: off

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: OpenXRay (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: kGVniXDR926BfVcA97y25BzALbijvgboBsozZzY9yc8RPz15Q4YG474h7vl14/J1
  artifact:
    openxray
  draft: true
  force_update: true
