# P&T SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=pttestc

PROG_OBJS = \
	../../../md5c.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../common/gsAvailable.o\
	../../../common/gsCrypt.o\
	../../../common/gsLargeInt.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsDebug.o\
	../../../common/gsXML.o\
	../../../common/gsRC4.o\
	../../../common/gsSHA1.o\
	../../../common/gsSSL.o\
	../../../common/gsMemory.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../ghttp/ghttpBuffer.o\
	../../../ghttp/ghttpCallbacks.o\
	../../../ghttp/ghttpConnection.o\
	../../../ghttp/ghttpMain.o\
	../../../ghttp/ghttpProcess.o\
	../../../ghttp/ghttpCommon.o\
	../../../ghttp/ghttpPost.o\
	../../../ghttp/ghttpEncryption.o\
	../../ptMain.o\
	../$(PROJECT).o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
