# Sake SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=saketest

DEFINES=-D_MACOSX -DGSI_NO_THREADS

PROG_OBJS = \
	../../../md5c.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../common/gsAssert.o\
	../../../common/gsAvailable.o\
	../../../common/gsCore.o\
	../../../common/gsDebug.o\
	../../../common/gsCrypt.o\
	../../../common/gsLargeInt.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsMemory.o\
	../../../common/gsXML.o\
	../../../common/gsSHA1.o\
	../../../common/gsRC4.o\
	../../../common/gsSSL.o\
	../../../common/gsSoap.o\
        ../../../common/gsUdpEngine.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../gp/gp.o\
	../../../gp/gpi.o\
	../../../gp/gpiBuddy.o\
	../../../gp/gpiBuffer.o\
	../../../gp/gpiCallback.o\
	../../../gp/gpiConnect.o\
	../../../gp/gpiInfo.o\
        ../../../gp/gpiKeys.o\
	../../../gp/gpiOperation.o\
	../../../gp/gpiPeer.o\
	../../../gp/gpiProfile.o\
	../../../gp/gpiSearch.o\
	../../../gp/gpiUnique.o\
	../../../gp/gpiUtility.o\
	../../../gp/gpiTransfer.o\
	../../../ghttp/ghttpBuffer.o\
	../../../ghttp/ghttpCallbacks.o\
	../../../ghttp/ghttpConnection.o\
	../../../ghttp/ghttpEncryption.o\
	../../../ghttp/ghttpMain.o\
	../../../ghttp/ghttpProcess.o\
	../../../ghttp/ghttpCommon.o\
	../../../ghttp/ghttpPost.o\
	../../../gt2/gt2Auth.o\
	../../../gt2/gt2Buffer.o\
	../../../gt2/gt2Callback.o\
	../../../gt2/gt2Connection.o\
	../../../gt2/gt2Filter.o\
	../../../gt2/gt2Main.o\
	../../../gt2/gt2Message.o\
	../../../gt2/gt2Socket.o\
	../../../gt2/gt2Encode.o\
	../../../gt2/gt2Utility.o\
	../../sakeMain.o\
	../../sakeRequest.o\
	../../sakeRequestMisc.o\
	../../sakeRequestModify.o\
	../../sakeRequestRead.o\
	../saketest.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
