GOA         = $(shell pwd)/../..

all:
	cd '$(GOA)/Chat/chatc/chatmacosx/' ; make clean
	cd '$(GOA)/Chat/chatc/chatmacosx/' ; make 
	cd '$(GOA)/Chat/chatc/chatmacosx/' ; make clean
	cd '$(GOA)/Chat/chatc/chatmacosx/' ; make unicode
	cd '$(GOA)/gcdkey/gcdkeymacosx/gcdkeyclientmacosx' ; make clean
	cd '$(GOA)/gcdkey/gcdkeymacosx/gcdkeyclientmacosx' ; make 
	cd '$(GOA)/gcdkey/gcdkeymacosx/gcdkeyservermacosx' ; make clean
	cd '$(GOA)/gcdkey/gcdkeymacosx/gcdkeyservermacosx' ; make 
	cd '$(GOA)/ghttp/ghttpc/ghttpmacosx/' ; make clean
	cd '$(GOA)/ghttp/ghttpc/ghttpmacosx/' ; make 
	cd '$(GOA)/ghttp/ghttpc/ghttpmacosx/' ; make clean
	cd '$(GOA)/ghttp/ghttpc/ghttpmacosx/' ; make unicode
	cd '$(GOA)/GP/gptestc/gpmacosx' ; make clean
	cd '$(GOA)/GP/gptestc/gpmacosx' ; make 
	cd '$(GOA)/GP/gptestc/gpmacosx' ; make clean
	cd '$(GOA)/GP/gptestc/gpmacosx' ; make unicode
	cd '$(GOA)/gstats/statstest/gstatsmacosx' ; make clean
	cd '$(GOA)/gstats/statstest/gstatsmacosx' ; make 
	cd '$(GOA)/gstats/statstest/gstatsmacosx' ; make clean
	cd '$(GOA)/gstats/statstest/gstatsmacosx' ; make unicode
	cd '$(GOA)/gstats/persisttest/persistmacosx' ; make clean
	cd '$(GOA)/gstats/persisttest/persistmacosx' ; make 
	cd '$(GOA)/gstats/persisttest/persistmacosx' ; make clean
	cd '$(GOA)/gstats/persisttest/persistmacosx' ; make unicode
	cd '$(GOA)/gt2/gt2testc/gt2macosx' ; make clean
	cd '$(GOA)/gt2/gt2testc/gt2macosx' ; make 
	cd '$(GOA)/gt2/gt2testc/gt2macosx' ; make clean
	cd '$(GOA)/gt2/gt2testc/gt2macosx' ; make unicode
	cd '$(GOA)/natneg/simpletest/natnegmacosx' ; make clean
	cd '$(GOA)/natneg/simpletest/natnegmacosx' ; make 
	cd '$(GOA)/Peer/peerc/peermacosx' ; make clean
	cd '$(GOA)/Peer/peerc/peermacosx' ; make 
	cd '$(GOA)/Peer/peerc/peermacosx' ; make clean
	cd '$(GOA)/Peer/peerc/peermacosx' ; make unicode
	cd '$(GOA)/pt/pttestc/ptmacosx' ; make clean
	cd '$(GOA)/pt/pttestc/ptmacosx' ; make 
	cd '$(GOA)/pt/pttestc/ptmacosx' ; make clean
	cd '$(GOA)/pt/pttestc/ptmacosx' ; make unicode
	cd '$(GOA)/qr2/qr2csample/qr2macosx' ; make clean
	cd '$(GOA)/qr2/qr2csample/qr2macosx' ; make 
	cd '$(GOA)/qr2/qr2csample/qr2macosx' ; make clean
	cd '$(GOA)/qr2/qr2csample/qr2macosx' ; make unicode
	cd '$(GOA)/serverbrowsing/sbctest/sbmacosx' ; make clean
	cd '$(GOA)/serverbrowsing/sbctest/sbmacosx' ; make 
	cd '$(GOA)/serverbrowsing/sbctest/sbmacosx' ; make clean
	cd '$(GOA)/serverbrowsing/sbctest/sbmacosx' ; make unicode
	cd '$(GOA)/Voice2/Voice2Test/gvmacosx' ; make clean
	cd '$(GOA)/Voice2/Voice2Test/gvmacosx' ; make 
	cd '$(GOA)/Voice2/voice2bench/voice2benchmacosx' ; make clean
	cd '$(GOA)/Voice2/voice2bench/voice2benchmacosx' ; make 
