find_path(DXSDK_INCLUDE_DIR
    NAMES d3dx9.h 
    PATHS "${CMAKE_SOURCE_DIR}/sdk/include"
    NO_DEFAULT_PATH
)

find_library(DXSDK_LIBRARY_IMPLIB_RELEASE
    NAMES d3dx9
    PATHS "${CMAKE_SOURCE_DIR}/sdk/libraries/${ARCH_TYPE}"
    NO_DEFAULT_PATH
)

find_file(DXSDK_LIBRARY_RELEASE
    NAMES D3DX9_43.dll
    PATHS "${CMAKE_SOURCE_DIR}/sdk/binaries/${ARCH_TYPE}"
    NO_DEFAULT_PATH
)

find_library(DXSDK_LIBRARY_IMPLIB_DEBUG
    NAMES d3dx9d
    PATHS "${CMAKE_SOURCE_DIR}/sdk/libraries/${ARCH_TYPE}"
    NO_DEFAULT_PATH
)

find_file(DXSDK_LIBRARY_DEBUG
    NAMES D3DX9d_43.dll
    PATHS "${CMAKE_SOURCE_DIR}/sdk/binaries/${ARCH_TYPE}"
    NO_DEFAULT_PATH
)

mark_as_advanced(
    DXSDK_INCLUDE_DIR
    DXSDK_LIBRARY_IMPLIB_RELEASE
    DXSDK_LIBRARY_IMPLIB_DEBUG
    DXSDK_LIBRARY_RELEASE
    DXSDK_LIBRARY_DEBUG
)

add_library(DXSDK_D3D9 STATIC IMPORTED GLOBAL)
add_library(DXSDK::D3D9 ALIAS DXSDK_D3D9)

set_target_properties(DXSDK_D3D9 PROPERTIES
    IMPORTED_IMPLIB_RELEASE "${DXSDK_LIBRARY_IMPLIB_RELEASE}"
    IMPORTED_IMPLIB_DEBUG "${DXSDK_LIBRARY_IMPLIB_DEBUG}"
    IMPORTED_LOCATION_RELEASE "${DXSDK_LIBRARY_RELEASE}"
    IMPORTED_LOCATION_DEBUG "${DXSDK_LIBRARY_DEBUG}"
    INTERFACE_INCLUDE_DIRECTORIES "${DXSDK_LIBRARY}"
)
