find_path(VORBIS_INCLUDE_DIR
    NAMES codec.h
    PATHS "${CMAKE_SOURCE_DIR}/sdk/include/vorbis"
    NO_DEFAULT_PATH
)

find_library(VORBIS_LIBRARY
    NAMES libvorbis_static
    PATHS "${CMAKE_SOURCE_DIR}/sdk/libraries/${ARCH_TYPE}"
    NO_CACHE
    NO_DEFAULT_PATH
    REQUIRED
)

add_library(VORBIS_VORBIS STATIC IMPORTED GLOBAL)
add_library(Vorbis::Vorbis ALIAS VORBIS_VORBIS)

set_target_properties(VORBIS_VORBIS PROPERTIES
    IMPORTED_LOCATION "${VORBIS_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${VORBIS_INCLUDE_DIR}"
)

find_path(VORBISFILE_INCLUDE_DIR
    NAMES vorbisfile.h
    PATHS "${CMAKE_SOURCE_DIR}/sdk/include/vorbis"
    NO_DEFAULT_PATH
)

find_library(VORBISFILE_LIBRARY
    NAMES libvorbisfile
    PATHS "${CMAKE_SOURCE_DIR}/sdk/libraries/${ARCH_TYPE}"
    NO_CACHE
    NO_DEFAULT_PATH
    REQUIRED
)

add_library(VORBISFILE_VORBISFILE STATIC IMPORTED GLOBAL)
add_library(Vorbis::VorbisFile ALIAS VORBISFILE_VORBISFILE)

set_target_properties(VORBISFILE_VORBISFILE PROPERTIES
    IMPORTED_LOCATION "${VORBISFILE_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${VORBISFILE_INCLUDE_DIR}"
)

mark_as_advanced(
    VORBIS_INCLUDE_DIR
    VORBIS_LIBRARY
    VORBISFILE_INCLUDE_DIR
    VORBISFILE_LIBRARY
)
