find_path(OPENAL_INCLUDE_DIR
    NAMES al.h
    PATHS "${CMAKE_SOURCE_DIR}/sdk/include/AL"
    NO_DEFAULT_PATH
)

find_library(OPENAL_LIBRARY
    NAMES OpenAL32
    PATHS "${CMAKE_SOURCE_DIR}/sdk/libraries/${ARCH_TYPE}"
    NO_DEFAULT_PATH
)

mark_as_advanced(
    OPENAL_INCLUDE_DIR
    OPENAL_LIBRARY
)

add_library(OPENAL_OPENAL STATIC IMPORTED GLOBAL)
add_library(OpenAL::OpenAL ALIAS OPENAL_OPENAL)

set_target_properties(OPENAL_OPENAL PROPERTIES
    IMPORTED_LOCATION "${OPENAL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENAL_INCLUDE_DIR}"
)
