// Borland C++ Builder
// Copyright (c) 1995, 2002 by Borland Software Corporation
// All rights reserved

// (DO NOT EDIT: machine generated header) 'dclelpB6.pas' rev: 6.00

#ifndef dclelpB6HPP
#define dclelpB6HPP

#pragma delphiheader begin
#pragma option push -w-
#pragma option push -Vx
#include <ColnEdit.hpp>	// Pascal unit
#include <ToolWnds.hpp>	// Pascal unit
#include <ElIPEdit.hpp>	// Pascal unit
#include <WinSock.hpp>	// Pascal unit
#include <ElClipMon.hpp>	// Pascal unit
#include <ElHTMLView.hpp>	// Pascal unit
#include <ElHTMLHint.hpp>	// Pascal unit
#include <ElTrayInfo.hpp>	// Pascal unit
#include <ElLabel.hpp>	// Pascal unit
#include <ElPromptDlg.hpp>	// Pascal unit
#include <ElNameEdits.hpp>	// Pascal unit
#include <ElFolderDlg.hpp>	// Pascal unit
#include <ElPgCtl.hpp>	// Pascal unit
#include <ElSplit.hpp>	// Pascal unit
#include <ElMouseHint.hpp>	// Pascal unit
#include <ElURLLabel.hpp>	// Pascal unit
#include <ElShellUtils.hpp>	// Pascal unit
#include <ElCLabel.hpp>	// Pascal unit
#include <ElVerInfo.hpp>	// Pascal unit
#include <ElTray.hpp>	// Pascal unit
#include <ElTimers.hpp>	// Pascal unit
#include <ElToolbar.hpp>	// Pascal unit
#include <frmTbrStp.hpp>	// Pascal unit
#include <ElStatBar.hpp>	// Pascal unit
#include <ElSideBar.hpp>	// Pascal unit
#include <ElExpBar.hpp>	// Pascal unit
#include <ElAdvPanel.hpp>	// Pascal unit
#include <ElHTMLPanel.hpp>	// Pascal unit
#include <ElStrToken.hpp>	// Pascal unit
#include <ElScrollBox.hpp>	// Pascal unit
#include <ElFontCombo.hpp>	// Pascal unit
#include <ElDriveCombo.hpp>	// Pascal unit
#include <ElTrackBar.hpp>	// Pascal unit
#include <ElImgCombo.hpp>	// Pascal unit
#include <ElCheckItemGrp.hpp>	// Pascal unit
#include <ElGroupBox.hpp>	// Pascal unit
#include <ElFileUtils.hpp>	// Pascal unit
#include <ElOneInst.hpp>	// Pascal unit
#include <ElBaseComp.hpp>	// Pascal unit
#include <ElMRU.hpp>	// Pascal unit
#include <ElMemoCombo.hpp>	// Pascal unit
#include <ElGauge.hpp>	// Pascal unit
#include <ElHstgrm.hpp>	// Pascal unit
#include <ElGraphs.hpp>	// Pascal unit
#include <ElCGControl.hpp>	// Pascal unit
#include <ElQueue.hpp>	// Pascal unit
#include <ElFlatCtl.hpp>	// Pascal unit
#include <ElInputDlg.hpp>	// Pascal unit
#include <ElDailyTip.hpp>	// Pascal unit
#include <ElHTMLLbl.hpp>	// Pascal unit
#include <ElStrPool.hpp>	// Pascal unit
#include <ElColorMap.hpp>	// Pascal unit
#include <frmColorMapItems.hpp>	// Pascal unit
#include <ElCRC32.hpp>	// Pascal unit
#include <ElClock.hpp>	// Pascal unit
#include <ElClrCmb.hpp>	// Pascal unit
#include <ElCaption.hpp>	// Pascal unit
#include <ElHotKey.hpp>	// Pascal unit
#include <ElBiProgr.hpp>	// Pascal unit
#include <ElAppBar.hpp>	// Pascal unit
#include <ElTreeTreeComboEdit.hpp>	// Pascal unit
#include <ElTreeCombo.hpp>	// Pascal unit
#include <ElImgLst.hpp>	// Pascal unit
#include <ElTreeSpinEdit.hpp>	// Pascal unit
#include <ElTreeMemoEdit.hpp>	// Pascal unit
#include <ElTreeMaskEdit.hpp>	// Pascal unit
#include <ElMaskEdit.hpp>	// Pascal unit
#include <ElTreeDTPickEdit.hpp>	// Pascal unit
#include <ElDTPick.hpp>	// Pascal unit
#include <ElCalendDlg.hpp>	// Pascal unit
#include <ElPanel.hpp>	// Pascal unit
#include <ElCombos.hpp>	// Pascal unit
#include <ElFrmPers.hpp>	// Pascal unit
#include <ElPropTools.hpp>	// Pascal unit
#include <ElMTree.hpp>	// Pascal unit
#include <ElListBox.hpp>	// Pascal unit
#include <ElSpin.hpp>	// Pascal unit
#include <ElCalendar.hpp>	// Pascal unit
#include <Grids.hpp>	// Pascal unit
#include <Mask.hpp>	// Pascal unit
#include <MaskUtils.hpp>	// Pascal unit
#include <ElCalendarDefs.hpp>	// Pascal unit
#include <ElSpinBtn.hpp>	// Pascal unit
#include <ElTreeCurrEdit.hpp>	// Pascal unit
#include <ElCurrEdit.hpp>	// Pascal unit
#include <ElTreeComboBox.hpp>	// Pascal unit
#include <HTMLLbx.hpp>	// Pascal unit
#include <ElTreeCheckBoxEdit.hpp>	// Pascal unit
#include <ElCheckCtl.hpp>	// Pascal unit
#include <ElHandPt.hpp>	// Pascal unit
#include <ElTreeAdvEdit.hpp>	// Pascal unit
#include <ElTreeModalEdit.hpp>	// Pascal unit
#include <ElTreeStdEditors.hpp>	// Pascal unit
#include <ElTreeGrids.hpp>	// Pascal unit
#include <ElTreeBtnEdit.hpp>	// Pascal unit
#include <ElBtnEdit.hpp>	// Pascal unit
#include <ElEdits.hpp>	// Pascal unit
#include <ElStrArray.hpp>	// Pascal unit
#include <ElTree.hpp>	// Pascal unit
#include <ElDragDrop.hpp>	// Pascal unit
#include <ElCBFmts.hpp>	// Pascal unit
#include <ElScrollBar.hpp>	// Pascal unit
#include <ElHintWnd.hpp>	// Pascal unit
#include <ElHeader.hpp>	// Pascal unit
#include <frmHdrStp.hpp>	// Pascal unit
#include <ElPopBtn.hpp>	// Pascal unit
#include <ElMenus.hpp>	// Pascal unit
#include <ElColor.hpp>	// Pascal unit
#include <ElSndMap.hpp>	// Pascal unit
#include <ElBtnCtl.hpp>	// Pascal unit
#include <HTMLRender.hpp>	// Pascal unit
#include <ElStack.hpp>	// Pascal unit
#include <ElXPThemedControl.hpp>	// Pascal unit
#include <ElACtrls.hpp>	// Pascal unit
#include <ElImgFrm.hpp>	// Pascal unit
#include <ElExtBkgnd.hpp>	// Pascal unit
#include <ElUxTheme.hpp>	// Pascal unit
#include <ElTmSchema.hpp>	// Pascal unit
#include <ElVCLUtils.hpp>	// Pascal unit
#include <ElUnicodeStrings.hpp>	// Pascal unit
#include <ElArray.hpp>	// Pascal unit
#include <ElHook.hpp>	// Pascal unit
#include <ElIni.hpp>	// Pascal unit
#include <ElObjList.hpp>	// Pascal unit
#include <ElList.hpp>	// Pascal unit
#include <ElContBase.hpp>	// Pascal unit
#include <ElRegUtils.hpp>	// Pascal unit
#include <ElTools.hpp>	// Pascal unit
#include <MMSystem.hpp>	// Pascal unit
#include <ElStrUtils.hpp>	// Pascal unit
#include <DsnConst.hpp>	// Pascal unit
#include <DesignWindows.hpp>	// Pascal unit
#include <VCLEditors.hpp>	// Pascal unit
#include <ComponentDesigner.hpp>	// Pascal unit
#include <TopLevels.hpp>	// Pascal unit
#include <StFilSys.hpp>	// Pascal unit
#include <TreeIntf.hpp>	// Pascal unit
#include <IStreams.hpp>	// Pascal unit
#include <AxCtrls.hpp>	// Pascal unit
#include <StdVCL.hpp>	// Pascal unit
#include <ComObj.hpp>	// Pascal unit
#include <ComConst.hpp>	// Pascal unit
#include <EditIntf.hpp>	// Pascal unit
#include <VirtIntf.hpp>	// Pascal unit
#include <Events.hpp>	// Pascal unit
#include <ToolUtils.hpp>	// Pascal unit
#include <ToolsAPI.hpp>	// Pascal unit
#include <ComCtrls.hpp>	// Pascal unit
#include <ExtActns.hpp>	// Pascal unit
#include <Mapi.hpp>	// Pascal unit
#include <Registry.hpp>	// Pascal unit
#include <ExtDlgs.hpp>	// Pascal unit
#include <Buttons.hpp>	// Pascal unit
#include <ComStrs.hpp>	// Pascal unit
#include <ListActns.hpp>	// Pascal unit
#include <ToolWin.hpp>	// Pascal unit
#include <RichEdit.hpp>	// Pascal unit
#include <Update.hpp>	// Pascal unit
#include <LibConst.hpp>	// Pascal unit
#include <Designer.hpp>	// Pascal unit
#include <DesignEditors.hpp>	// Pascal unit
#include <Proxies.hpp>	// Pascal unit
#include <DesignConst.hpp>	// Pascal unit
#include <DesignIntf.hpp>	// Pascal unit
#include <DesignMenus.hpp>	// Pascal unit
#include <IniFiles.hpp>	// Pascal unit
#include <Forms.hpp>	// Pascal unit
#include <WinHelpViewer.hpp>	// Pascal unit
#include <StdActns.hpp>	// Pascal unit
#include <StrUtils.hpp>	// Pascal unit
#include <Clipbrd.hpp>	// Pascal unit
#include <Dialogs.hpp>	// Pascal unit
#include <Dlgs.hpp>	// Pascal unit
#include <ExtCtrls.hpp>	// Pascal unit
#include <CommDlg.hpp>	// Pascal unit
#include <ShlObj.hpp>	// Pascal unit
#include <UrlMon.hpp>	// Pascal unit
#include <WinInet.hpp>	// Pascal unit
#include <RegStr.hpp>	// Pascal unit
#include <ShellAPI.hpp>	// Pascal unit
#include <StdCtrls.hpp>	// Pascal unit
#include <FlatSB.hpp>	// Pascal unit
#include <Printers.hpp>	// Pascal unit
#include <WinSpool.hpp>	// Pascal unit
#include <HelpIntfs.hpp>	// Pascal unit
#include <Menus.hpp>	// Pascal unit
#include <ActnList.hpp>	// Pascal unit
#include <Controls.hpp>	// Pascal unit
#include <Imm.hpp>	// Pascal unit
#include <MultiMon.hpp>	// Pascal unit
#include <ImgList.hpp>	// Pascal unit
#include <CommCtrl.hpp>	// Pascal unit
#include <Contnrs.hpp>	// Pascal unit
#include <Math.hpp>	// Pascal unit
#include <Graphics.hpp>	// Pascal unit
#include <Consts.hpp>	// Pascal unit
#include <Classes.hpp>	// Pascal unit
#include <ActiveX.hpp>	// Pascal unit
#include <TypInfo.hpp>	// Pascal unit
#include <RTLConsts.hpp>	// Pascal unit
#include <Variants.hpp>	// Pascal unit
#include <VarUtils.hpp>	// Pascal unit
#include <SysUtils.hpp>	// Pascal unit
#include <SysConst.hpp>	// Pascal unit
#include <Messages.hpp>	// Pascal unit
#include <Windows.hpp>	// Pascal unit
#include <Types.hpp>	// Pascal unit
#include <TreeDsgn.hpp>	// Pascal unit
#include <ElEBDsgn.hpp>	// Pascal unit
#include <ElMenuDsgn.hpp>	// Pascal unit
#include <PgCtlProp.hpp>	// Pascal unit
#include <ColnProp.hpp>	// Pascal unit
#include <ElImageIndexProp.hpp>	// Pascal unit
#include <frmStrPoolEdit.hpp>	// Pascal unit
#include <frmSectProp.hpp>	// Pascal unit
#include <frmSectEdit.hpp>	// Pascal unit
#include <frmItemCol.hpp>	// Pascal unit
#include <frmItemsProp.hpp>	// Pascal unit
#include <ColorMapProp.hpp>	// Pascal unit
#include <frmSoundMap.hpp>	// Pascal unit
#include <ElTBDsgn.hpp>	// Pascal unit
#include <MlCapProp.hpp>	// Pascal unit
#include <frmFormPers.hpp>	// Pascal unit
#include <ElReg.hpp>	// Pascal unit
#include <SysInit.hpp>	// Pascal unit
#include <System.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Dclelpb6
{
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------

}	/* namespace Dclelpb6 */
using namespace Dclelpb6;
#pragma option pop	// -w-
#pragma option pop	// -Vx

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// dclelpB6
