# Query & Reporting 2 SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=qr2csample

PROG_OBJS = \
	../../../hashtable.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsMemory.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../natneg/natneg.o\
	../../../natneg/NATify.o\
	../../qr2.o\
	../../qr2regkeys.o\
	../qr2csample.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
