#ifndef CONFIGURATOR_DEFINES_H
#define CONFIGURATOR_DEFINES_H
#define SS_DUST
#define USE_VOLUMETRIC_DUST
#define USE_MOON_ROAD
#define FL_USE_LONG_FLARE
//#define SSDO_USE_INDIRECT_BOUNCES
//#define DDOF_VIGNETTING
//#define DDOF_CHROMATIC_ABERRATION

#define SS_VOL_MAX_INTENSITY float(0.100)
#define VOL_LIGHT_MAX_INTENSITY float(0.015)
#define SSDO_BLEND_FACTOR float(1.500)
#define HBAO_BLEND_FACTOR float(0.700)
#define DDOF_VIGNOUT float(0.000)
#define DDOF_GAIN float(1.000)
#define ZDOF_INTENSITY float(0.600)
#define RDOF_INTENSITY float(0.400)
#define PUDDLES_GROW_SPEED float(0.500)
#endif
