package org.openxray.app;

// Generated by android/apk/generate-options.py from launcher-options.json.
final class OptionCatalog {
    private OptionCatalog() {}

    static final String[] GAME_LABELS = { "Автоматически / без ключа", "Shadow of Chernobyl (-soc)", "Clear Sky (-cs)", "Call of Pripyat (-cop)" };
    static final String[] GAME_NAMES = { "автоопределение", "Shadow of Chernobyl", "Clear Sky", "Call of Pripyat" };
    static final String[] GAME_ARGS = { "", "-soc", "-cs", "-cop" };

    static final String[] RENDERER_LABELS = { "Автоматически (OpenGL ES)", "OpenGL ES", "Vulkan (экспериментальный fallback)" };
    static final String[] RENDERER_ARGS = { "-renderer-auto", "-renderer-gles", "-renderer-vulkan" };

    static final String[] GRAPHICS_LABELS = { "Автоматически для Android (Low)", "Minimum", "Low", "Default", "High", "Extreme" };
    static final String[] GRAPHICS_PRESETS = { "Low", "Minimum", "Low", "Default", "High", "Extreme" };

    static final String[] TABS = { "Игра", "Параметры", "Диагностика" };
    static final String[] SETTINGS_SECTIONS = { "Рендерер", "Графика", "Разрешение 3D-рендера", "Управление и экран", "Расширенные параметры", "Дополнительные аргументы" };
    static final int[] RESOLUTION_WIDTHS = { 854, 960, 1280, 1600, 1920, 2240, 2560 };
    static final String ADVANCED_RESET_LABEL = "Сбросить диагностические параметры";
    static final String[] ADVANCED_KEYS = { "disable_hom", "disable_occq", "gl_debug" };
    static final String[] ADVANCED_LABELS = { "Отключить программное отсечение HOM", "Отключить GPU-запросы видимости", "Подробные сообщения OpenGL" };
    static final String[] ADVANCED_DESCRIPTIONS = { "Проверка ошибок видимости; может снизить FPS.", "Проверка ошибок драйвера; может снизить FPS.", "Записывает ошибки драйвера в журнал; может снизить FPS." };
    static final String[] ADVANCED_ARGS = { "-no_hom", "-no_occq", "-android-gl-debug" };

    static String value(String[] values, int index, int fallback) {
        return values[index >= 0 && index < values.length ? index : fallback];
    }
}
