package org.openxray.app;

// Generated by android/apk/generate-options.py from launcher-options.json.
final class OptionCatalog {
    private OptionCatalog() {}

    static final String[] GAME_LABELS = { "Автоматически / без ключа", "Shadow of Chernobyl (-soc)", "Clear Sky (-cs)", "Call of Pripyat (-cop)" };
    static final String[] GAME_NAMES = { "автоопределение", "Shadow of Chernobyl", "Clear Sky", "Call of Pripyat" };
    static final String[] GAME_ARGS = { "", "-soc", "-cs", "-cop" };

    static final String[] RENDERER_LABELS = { "Автоматически (OpenGL ES)", "OpenGL ES", "Vulkan (игровой рендерер в разработке)" };
    static final String[] RENDERER_ARGS = { "-renderer-auto", "-renderer-gles", "-renderer-vulkan" };

    static final String[] GRAPHICS_LABELS = { "Автоматически для Android (Low)", "Minimum", "Low", "Default", "High", "Extreme" };
    static final String[] GRAPHICS_PRESETS = { "Low", "Minimum", "Low", "Default", "High", "Extreme" };

    static final String[] TABS = { "Игра", "Параметры", "Диагностика" };
    static final String[] SETTINGS_SECTIONS = { "Рендерер", "Качество рендеринга", "Разрешение 3D-рендера", "Управление и экран", "Дополнительные аргументы" };

    static String value(String[] values, int index, int fallback) {
        return values[index >= 0 && index < values.length ? index : fallback];
    }
}
