# CDKey SDK Client Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=gcdkeyclient

PROG_OBJS = \
	../../../md5c.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsStringUtil.o\
	../../../common/gsDebug.o\
	../../../common/gsMemory.o\
	../../../common/macosx/MacOSXCommon.o\
	../../gcdkeyc.o\
	../../ClientTest/gcdkeyclienttest.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
