#!/usr/bin/env python3
"""Generate the launcher labels and native argument catalog from one file."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TARGET = ROOT / "app/src/main/java/org/openxray/app/OptionCatalog.java"


def java_string(value):
    return json.dumps(value, ensure_ascii=False).replace("\\u2028", "\\u2028")


def generate(options):
    required = {"game": ("label", "name", "arg"),
                "renderer": ("label", "arg"),
                "graphics": ("label", "preset")}
    if set(options) != set(required):
        raise ValueError("unexpected catalog categories")
    lines = ["package org.openxray.app;", "",
             "// Generated by android/apk/generate-options.py from launcher-options.json.",
             "final class OptionCatalog {", "    private OptionCatalog() {}", ""]
    for category, fields in required.items():
        entries = options[category]
        if not entries or any(set(entry) != set(fields) for entry in entries):
            raise ValueError("invalid options for " + category)
        for field in fields:
            name = category.upper() + "_" + field.upper() + "S"
            values = ", ".join(java_string(entry[field]) for entry in entries)
            lines.append("    static final String[] " + name + " = { " + values + " };")
        lines.append("")
    lines += ["    static String value(String[] values, int index, int fallback) {",
              "        return values[index >= 0 && index < values.length ? index : fallback];",
              "    }", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(json.loads((ROOT / "launcher-options.json").read_text(encoding="utf-8")))
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != rendered:
            parser.error("OptionCatalog.java is stale; run generate-options.py")
    else:
        TARGET.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
