#!/usr/bin/env python3
"""Generate the launcher labels and native argument catalog from one file."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TARGET = ROOT / "app/src/main/java/org/openxray/app/OptionCatalog.java"


def java_string(value):
    return json.dumps(value, ensure_ascii=False).replace("\\u2028", "\\u2028")


def generate(options):
    required = {"game": ("label", "name", "arg"),
                "renderer": ("label", "arg"),
                "graphics": ("label", "preset")}
    if set(options) != set(required) | {"resolution_widths", "tabs", "settings_sections", "advanced", "advanced_reset_label", "quality_overrides"}:
        raise ValueError("unexpected catalog categories")
    lines = ["package org.openxray.app;", "",
             "// Generated by android/apk/generate-options.py from launcher-options.json.",
             "final class OptionCatalog {", "    private OptionCatalog() {}", ""]
    for category, fields in required.items():
        entries = options[category]
        if not entries or any(set(entry) != set(fields) for entry in entries):
            raise ValueError("invalid options for " + category)
        for field in fields:
            name = category.upper() + "_" + field.upper() + "S"
            values = ", ".join(java_string(entry[field]) for entry in entries)
            lines.append("    static final String[] " + name + " = { " + values + " };")
        lines.append("")
    for category in ("tabs", "settings_sections"):
        entries = options[category]
        if not entries or any(not isinstance(entry, str) for entry in entries):
            raise ValueError("invalid " + category)
        lines.append("    static final String[] " + category.upper() + " = { "
                     + ", ".join(map(java_string, entries)) + " };")
    widths = options["resolution_widths"]
    if not widths or any(not isinstance(width, int) or width < 320 for width in widths):
        raise ValueError("invalid resolution widths")
    lines.append("    static final int[] RESOLUTION_WIDTHS = { "
                 + ", ".join(map(str, widths)) + " };")
    lines.append("    static final String ADVANCED_RESET_LABEL = "
                 + java_string(options["advanced_reset_label"]) + ";")
    entries = options["advanced"]
    if not entries or any(set(entry) != {"key", "label", "description", "arg"} for entry in entries):
        raise ValueError("invalid advanced options")
    for field in ("key", "label", "description", "arg"):
        lines.append("    static final String[] ADVANCED_" + field.upper() + "S = { "
                     + ", ".join(java_string(entry[field]) for entry in entries) + " };")
    lines += ["", "    static String value(String[] values, int index, int fallback) {",
              "        return values[index >= 0 && index < values.length ? index : fallback];",
              "    }", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    options = json.loads((ROOT / "launcher-options.json").read_text(encoding="utf-8"))
    rendered = generate(options)
    profiles = options["quality_overrides"]
    if set(profiles) != {item["preset"] for item in options["graphics"]}:
        parser.error("quality overrides must cover every graphics preset")
    for preset, commands in profiles.items():
        if not preset.isalpha() or any("\n" in key + value for key, value in commands.items()):
            parser.error("invalid quality profile")
        target = ROOT / ("quality_" + preset.lower() + ".ltx")
        text = "; Generated from launcher-options.json.\n" + "".join(
            key + " " + value + "\n" for key, value in commands.items())
        if args.check:
            if not target.exists() or target.read_text() != text:
                parser.error(str(target) + " is stale")
        else:
            target.write_text(text)

    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != rendered:
            parser.error("OptionCatalog.java is stale; run generate-options.py")
    else:
        TARGET.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
