# Peer SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=peerc

PROG_OBJS = \
	../../../hashtable.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsMemory.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../Chat/chatCallbacks.o\
	../../../Chat/chatChannel.o\
	../../../Chat/chatCrypt.o\
	../../../Chat/chatHandlers.o\
	../../../Chat/chatMain.o\
	../../../Chat/chatSocket.o\
	../../../pinger/pingerMain.o\
	../../../serverbrowsing/sb_crypt.o\
	../../../serverbrowsing/sb_queryengine.o\
	../../../serverbrowsing/sb_server.o\
	../../../serverbrowsing/sb_serverbrowsing.o\
	../../../serverbrowsing/sb_serverlist.o\
	../../../qr2/qr2.o\
	../../../qr2/qr2regkeys.o\
	../../../natneg/natneg.o\
	../../../natneg/NATify.o\
	../../peerAutoMatch.o\
	../../peerCallbacks.o\
	../../peerGlobalCallbacks.o\
	../../peerHost.o\
	../../peerKeys.o\
	../../peerMain.o\
	../../peerMangle.o\
	../../peerOperations.o\
	../../peerPing.o\
	../../peerPlayers.o\
	../../peerQR.o\
	../../peerRooms.o\
	../../peerSB.o\
	../peerc.o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
