///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Header File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

#define ATLAS_RULE_SET_VERSION 1

// KEYS
// Use these key ID's to report match data for your game.

#define RACE_TIME 1  // Player's race time for the match (milliseconds).

///////////////////////////////////////////////////////////////////////////////

// STATS
// Use these stat ID's to query aggregate statistics for your game.

#define CAREER_WINS 1  
#define CAREER_LOSSES 2  
#define BEST_RACE_TIME 3  // Player's career best race time (milliseconds).
#define WORST_RACE_TIME 4  // Player's career worst race time (milliseconds).
#define TOTAL_MATCHES 5  
#define AVERAGE_RACE_TIME 6  // Player's average race time per match (milliseconds/match).
#define CURRENT_WIN_STREAK 7  
#define CURRENT_LOSS_STREAK 8  
#define TOTAL_RACE_TIME 9  // Player's total race time for all matches (milliseconds).