/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.5-0-g2eef7ca47 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.5-0-g2eef7ca47"
#endif
#define SDL_REVISION_NUMBER 0
