# Chat SDK Makefile - Mac OS X
# Copyright 2006 GameSpy Industries

PROJECT=chatc

PROG_OBJS = \
	../../../darray.o\
	../../../hashtable.o\
	../../../md5c.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsStringUtil.o\
	../../../common/gsDebug.o\
	../../../common/gsMemory.o\
	../../../common/macosx/MacOSXCommon.o\
	../../chatCallbacks.o\
	../../chatCrypt.o\
	../../chatChannel.o\
	../../chatHandlers.o\
	../../chatMain.o\
	../../chatSocket.o\
	../chatc.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
