
------ bandit_companion_task_1

function bandit_companion_task_1_complete(a,b)
	local squad = get_story_squad("bandit_companion_task_1")
	if not (squad) then 
		return false
	end
	
	local id = squad:commander_id()
	local npc = db.storage[id] and db.storage[id].object
	if not (npc) then 
		return false
	end
	
	local total_loot_count = 0
	for k in squad:squad_members() do
		local npc = db.storage[k.id] and db.storage[k.id].object
		if (npc) then 
			total_loot_count = total_loot_count + (utils.load_var(npc,"s_loot_count") or 0)
		end
	end
	
	if (total_loot_count >= 9) then 
		return true
	end
	
	return false
end

function bandit_companion_task_1_not_complete(a,b)
	return not bandit_companion_task_1_complete(a,b)
end 

function bandit_companion_task_1_complete_task(a,b)
	task_manager.get_task_manager():set_task_completed("val_smart_terrain_7_4_bandit_trader_stalker_task_3")
	a:stop_talk()
	b:stop_talk()
end

function bandit_companion_task_1_give_reward(a,b)
	dialogs.relocate_money(db.actor,math.random(2500,4000),"in")
	game_relations.change_factions_community_num("bandit",0,50)
end
