//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.11.519.0000
//
//   fxc /nologo /Tps_2_0 /Emain_ps_1_1 /Zpr /Fctest\p20_postprocess.ps
//    postprocess.ps
//
//
// Parameters:
//
//   float4 c_brightness;
//   sampler2D s_base0;
//   sampler2D s_base1;
//   sampler2D s_noise;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   c_brightness c0       1
//   s_base0      s0       1
//   s_base1      s1       1
//   s_noise      s2       1
//

    ps_2_0
    def c1, 0.5, 2, 1, 0
    dcl v0
    dcl v1
    dcl_pp t0.xy
    dcl_pp t1.xy
    dcl_pp t2.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    texld_pp r1, t0, s0
    texld_pp r2, t1, s1
    texld_pp r0, t2, s2
    add_pp r1.xyz, r1, r2
    mul_pp r2.xyz, r1, c1.x
    dp3_pp r2.x, r2, v1
    mad_pp r1.xyz, r1, c1.x, -r2.x
    mad_pp r2.xyz, v1.w, r1, r2.x
    mul_pp r1.xyz, r0, r2
    mad_pp r0.xyz, c1.y, -r1, r2
    add_pp r1.xyz, r1, r1
    mad_pp r0.xyz, v0.w, r0, r1
    mad_pp r0.xyz, r0, v0, c0
    add_pp r0.xyz, r0, r0
    mov r0.w, c1.z
    mov_pp oC0, r0

// approximately 16 instruction slots used (3 texture, 13 arithmetic)
