-- @ Version: SCREEN SPACE SHADERS - UPDATE 12
-- @ Description: SSS Main script - Settings
-- @ Author: https://www.moddb.com/members/ascii1457
-- @ Mod: https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders

-- If you're not using MCM you can customize your settings here --
ssfx_default_settings = {

	["shaderscope_patch"]		= false	-- Enable/Disable SHADER BASED 2D SCOPES support
}