#pragma once
#include "../XrECore/stdafx.h"
#include "../XrECore/Editor/device.h"
#include "../XrECore/Editor/UI_MainCommand.h"
#include "../XrECore/Editor/UI_ToolsCustom.h"
#include "../XrECore/Editor/ui_main.h"
#include "../XrECore/Editor/GeometryCollector.h"
#include "../XrECore/Editor/EditorPreferences.h"
#include "../XrECore/Editor/render.h"
#include "../XrECore/Editor/UIRenderForm.h"
#include "../XrECore/Editor/ELog.h"
#include "../XrECore/Editor/tlsprite.h"
#include "../XrECore/Editor/EditObject.h"
#include "../XrECore/Editor/EditMesh.h"
#include "../XrECore/Editor/D3DUtils.h"
#include "../XrEcore/Editor/PhysicsShellHolderEditorBase.h"
#include "../XrETools/ETools.h"
#include "../XrECore/Engine/Texture.h"
#include "../XrECore/Editor/Library.h"
#include "../XrECore/Editor/ImageManager.h"
#include "../XrECore/Editor/pick_defs.h"
#include "../XrECore/Editor/SoundManager.h"
#include "../XrECore/Editor/EDetailModel.h"
#include "../XrECore/Engine/Image.h"
#include "../XrECore/Engine/guid_generator.h"
#include "../XrECore/Editor/ExportSkeleton.h"
#include "../FreeMagic/MgcAppr3DPlaneFit.h"
#include "../FreeMagic/MgcEigen.h"
#include "../FreeMagic/MgcLinearSystem.h"
#include "../FreeMagic/MgcConvexHull2D.h"

#include "../XrCore/doug_lea_allocator.h"
#include "../XrCore/FixedMap.h"

#include "LightAnimLibrary.h"
#include "motion.h"
#include "envelope.h"
#include "communicate.h"
#include "xrHemisphere.h"
#include "../xrServerEntities/LevelGameDef.h"
#include "SkeletonAnimated.h"
#include "ObjectAnimator.h"
#include "xr_efflensflare.h"
#include "du_box.h"
#include "Communicate.h"
#include "xrLevel.h"

#include "..\..\XrCDB\xrCDB.h"
#include "..\..\XrCDB\ISpatial.h"
#include "..\..\XrRender\Public\ParticleCustom.h"
#include "..\..\XrRender\Private\DetailManager.h"
#include "..\..\XrRender\Private\ParticleEffect.h"
#include "..\..\XrRender\Private\ParticleEffectDef.h"
#include "..\..\XrRender\Private\ParticleGroup.h"

#include "cl_intersect.h"
#include "../xrServerEntities/xrMessages.h"
#include "../xrServerEntities/ShapeData.h"
#include "../xrServerEntities/xrServer_Objects_Abstract.h"

#ifndef _DEBUG
#define USE_ARENA_ALLOCATOR
#endif

#include "UI/UITopBarForm.h"
#include "UI/UIMainMenuForm.h"
#include "UI/UILeftBarForm.h"
#include "UI/UILPropertiesFrom.h"
#include "UI/UIMainForm.h"
#include "UI/Tools/UIToolCustom.h"
#include "UI/UIPropertiesModal.h"
#include "UI/Tools/UIShapeTool.h"
#include "UI/UIEditLibrary.h"

#include "Tools/ESceneClassList.h"

#include "UI_LevelMain.h"
#include "UI_LevelTools.h"

#include "Utils/Cursor3D.h"
#include "Utils/portalutils.h"
#include "Utils/iniStreamImpl.h"
#include "Utils/SoundManager_LE.h"
#include "Utils/LevelPreferences.h"
#include "Utils/Custom2DProjector.h"
#include "Utils/GeometryPartExtractor.h"

#include "Entry/CustomObject.h"
#include "Entry/Glow/glow.h"
#include "Entry/Group/GroupObject.h"
#include "Entry/Light/ELight.h"
#include "Entry/Particles/EParticlesObject.h"
#include "Entry/Portal/portal.h"
#include "Entry/Sector/sector.h"
#include "Entry/Shape/EShape.h"
#include "Entry/Sound/ESound_Environment.h"
#include "Entry/Sound/ESound_Source.h"
#include "Entry/Spawn/SpawnPoint.h"
#include "Entry/StaticObject/SceneObject.h"
#include "Entry/WayPoint/WayPoint.h"

#include "Tools/Base/ESceneControlsCustom.h"
#include "Tools/Base/ESceneCustomMTools.h"
#include "Tools/Base/ESceneCustomOTools.h"
#include "Tools/Base/ESceneDummyTools.h"

#include "Tools/AIMap/ESceneAIMapTools_Export.h"
#include "Tools/AIMap/ESceneAIMapTools.h"
#include "Tools/AIMap/ESceneAIMapControls.h"
#include "Tools/Details/ESceneDOTools.h"
#include "Tools/FogVolume/ESceneFogVolumeTools.h"
#include "Tools/Group/ESceneGroupTools.h"
#include "Tools/Group/ESceneGroupControls.h"
#include "Tools/Light/ESceneLightTools.h"
#include "Tools/Particles/EScenePSTools.h"
#include "Tools/Particles/EScenePSControls.h"
#include "Tools/Sector/ESceneSectorTools.h"
#include "Tools/Sector/ESceneSectorControls.h"
#include "Tools/Portal/EScenePortalTools.h"
#include "Tools/Portal/EScenePortalControls.h"
#include "Tools/Shape/ESceneShapeTools.h"
#include "Tools/Shape/ESceneShapeControls.h"
#include "Tools/Sound/ESceneSoundSrcTools.h"
#include "Tools/Sound/ESceneSoundEnvTools.h"
#include "Tools/Spawn/ESceneSpawnTools.h"
#include "Tools/Spawn/ESceneSpawnControls.h"
#include "Tools/StaticObject/ESceneObjectTools.h"
#include "Tools/StaticObject/ESceneObjectControls.h"
#include "Tools/Wallmark/ESceneWallmarkTools.h"
#include "Tools/Wallmark/ESceneWallmarkControls.h"
#include "Tools/WayPoint/ESceneWayTools.h"
#include "Tools/WayPoint/ESceneWayControls.h"
#include "Tools/Glow/ESceneGlowTools.h"

#include "Scene/scene.h"
#include "Scene/LEPhysics.h"
#include "Scene/SceneGraph.h"
#include "Scene/SceneSummaryInfo.h"
#include "Builder/Builder.h"

#include "UI/UIDOOneColor.h"
#include "UI/UIDOShuffle.h"
#include "UI/UIObjectList.h"

#include "UI/Tools/UIAIMapTool.h"
#include "UI/Tools/UIDOTool.h"
#include "UI/Tools/UIFogVolTool.h"
#include "UI/Tools/UIGroupTool.h"
#include "UI/Tools/UILightTool.h"
#include "UI/Tools/UIObjectTool.h"
#include "UI/Tools/UIParticlesTool.h"
#include "UI/Tools/UIPortalTool.h"
#include "UI/Tools/UISectorTool.h"
#include "UI/Tools/UISpawnTool.h"
#include "UI/Tools/UIWayTool.h"
