/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.28.5-0-g15ead9a40 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.28.5-0-g15ead9a40"
#endif
#define SDL_REVISION_NUMBER 0
