# GameSpy Transport 2 SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=gt2testc

PROG_OBJS = \
	../../../hashtable.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsMemory.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/macosx/MacOSXCommon.o\
	../../gt2Auth.o\
	../../gt2Buffer.o\
	../../gt2Callback.o\
	../../gt2Connection.o\
	../../gt2Filter.o\
	../../gt2Main.o\
	../../gt2Message.o\
	../../gt2Socket.o\
	../../gt2Encode.o\
	../../gt2Utility.o\
	../gt2testc.o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
