# NAT Negotiation SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=simpletest

PROG_OBJS = \
	../../../hashtable.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsMemory.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/macosx/MacOSXCommon.o\
	../../natneg.o\
	../../NATify.o\
	../simpletest.o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
