plugins {
    id 'com.android.application'
}

def portVersion = rootProject.file('android-version.txt').readLines('UTF-8')
def exportShadersXr = providers.gradleProperty('xrayExportShadersXr').map { it.toBoolean() }.orElse(false).get()
if (portVersion.size() != 2 || !(portVersion[0] ==~ /\d+\.\d+\.\d+/) || !(portVersion[1] ==~ /\d+/)) {
    throw new GradleException('Invalid Android version file')
}

android {
    namespace 'org.openxray.app'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'org.openxray.stalker'
        minSdk 26
        targetSdk 36
        versionCode portVersion[1].toInteger()
        versionName portVersion[0]
        buildConfigField 'boolean', 'EXPORT_SHADERS_XR', exportShadersXr.toString()

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}
