#include "StdAfx.h"
#include "JoltDynamicsWorld.h"
#include "PHIsland.h"

// xr_types.h replaces FLT_MAX. Jolt needs the standard numeric macro.
#pragma push_macro("FLT_MAX")
#undef FLT_MAX
#define FLT_MAX 3.402823466e+38F
#include <Jolt/Jolt.h>
#include <Jolt/RegisterTypes.h>
#include <Jolt/Core/Factory.h>
#include <Jolt/Core/JobSystemThreadPool.h>
#include <Jolt/Core/TempAllocator.h>
#include <Jolt/Physics/PhysicsSystem.h>
#include <Jolt/Physics/Body/BodyCreationSettings.h>
#include <Jolt/Physics/Body/MotionProperties.h>
#include <Jolt/Physics/Collision/Shape/SphereShape.h>
#include <Jolt/Physics/Constraints/TwoBodyConstraint.h>
#pragma pop_macro("FLT_MAX")

#include <array>
#include <cstdarg>
#include <limits>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace
{
void TraceJolt(pcstr format, ...)
{
    char message[1024];
    va_list arguments;
    va_start(arguments, format);
    std::vsnprintf(message, sizeof(message), format, arguments);
    va_end(arguments);
    Msg("* Jolt dynamics: %s", message);
}

// One registration per xrPhysics module. The collision DLL has its own static
// Jolt library; its tree-only use does not share this factory or physics world.
struct JoltRuntime
{
    JoltRuntime()
    {
        JPH::RegisterDefaultAllocator();
        JPH::Trace = TraceJolt;
        JPH::Factory::sInstance = new JPH::Factory;
        JPH::RegisterTypes();
    }

    ~JoltRuntime()
    {
        JPH::UnregisterTypes();
        delete JPH::Factory::sInstance;
        JPH::Factory::sInstance = nullptr;
    }
};

// Contacts are generated by the engine's existing collision/material callback
// path and supplied as constraints. Suppress Jolt's own collision pairs to avoid
// generating a second, incompatible response for the same contact.
class BroadPhaseLayers final : public JPH::BroadPhaseLayerInterface
{
public:
    JPH::uint GetNumBroadPhaseLayers() const override { return 1; }
    JPH::BroadPhaseLayer GetBroadPhaseLayer(JPH::ObjectLayer) const override { return JPH::BroadPhaseLayer(0); }
#if defined(JPH_EXTERNAL_PROFILE) || defined(JPH_PROFILE_ENABLED)
    const char* GetBroadPhaseLayerName(JPH::BroadPhaseLayer) const override { return "ExternalContacts"; }
#endif
};

class ObjectBroadPhaseFilter final : public JPH::ObjectVsBroadPhaseLayerFilter
{
public:
    bool ShouldCollide(JPH::ObjectLayer, JPH::BroadPhaseLayer) const override { return false; }
};

class ObjectPairFilter final : public JPH::ObjectLayerPairFilter
{
public:
    bool ShouldCollide(JPH::ObjectLayer, JPH::ObjectLayer) const override { return false; }
};

JPH::Vec3 Vector(const dReal* value) { return JPH::Vec3(value[0], value[1], value[2]); }

void Store(JPH::Vec3Arg value, dReal* destination)
{
    destination[0] = value.GetX();
    destination[1] = value.GetY();
    destination[2] = value.GetZ();
    destination[3] = 0;
}

JPH::MassProperties Mass(const dxBody& body)
{
    JPH::MassProperties properties;
    properties.mMass = body.mass.mass;
    const auto* inertia = body.mass.I;
    properties.mInertia = JPH::Mat44(
        JPH::Vec4(inertia[0], inertia[4], inertia[8], 0),
        JPH::Vec4(inertia[1], inertia[5], inertia[9], 0),
        JPH::Vec4(inertia[2], inertia[6], inertia[10], 0),
        JPH::Vec4(0, 0, 0, 1));
    return properties;
}

struct BridgeSettings final : JPH::TwoBodyConstraintSettings
{
    JPH::TwoBodyConstraint* Create(JPH::Body&, JPH::Body&) const override { return nullptr; }
};

// Translate the legacy joint definition, not its solver. Every engine joint
// (including contacts, motors and stop limits) publishes at most six Jacobian
// rows. Jolt owns island building, integration and scheduling; these rows
// preserve game-specific ERP/CFM and friction semantics during migration.
class JointConstraint final : public JPH::TwoBodyConstraint
{
    struct Row
    {
        JPH::Vec3 linear1, angular1, linear2, angular2;
        JPH::Vec3 deltaLinear1, deltaAngular1, deltaLinear2, deltaAngular2;
        float targetVelocity = 0;
        float softness = 0;
        float lower = 0;
        float upper = 0;
        float effectiveMass = 0;
        float impulse = 0;
        int frictionRow = -1;
    };

public:
    JointConstraint(JPH::Body& first, JPH::Body& second, dxJoint& source, float step)
        : TwoBodyConstraint(first, second, BridgeSettings{}), source(source)
    {
        dxJoint::Info1 dimensions{};
        source.vtable->getInfo1(&source, &dimensions);
        count = dimensions.m;
        R_ASSERT2(count >= 0 && count <= 6, "Invalid joint row count");
        if (count == 0)
            return;

        std::array<std::array<dReal, 12>, 6> jacobian{};
        std::array<dReal, 6> target{}, softness{}, lower{}, upper{};
        std::array<int, 6> friction{};
        // The modified ODE stores these settings globally, but its Debug
        // getters still require a non-null world handle.
        softness.fill(dWorldGetCFM(source.node[0].body->world));
        lower.fill(-std::numeric_limits<dReal>::infinity());
        upper.fill(std::numeric_limits<dReal>::infinity());
        friction.fill(-1);
        dxJoint::Info2 info{};
        info.fps = 1 / step;
        info.erp = dWorldGetERP(source.node[0].body->world);
        info.rowskip = 12;
        info.J1l = jacobian[0].data();
        info.J1a = info.J1l + 3;
        info.J2l = info.J1l + 6;
        info.J2a = info.J1l + 9;
        info.c = target.data();
        info.cfm = softness.data();
        info.lo = lower.data();
        info.hi = upper.data();
        info.findex = friction.data();
        source.vtable->getInfo2(&source, &info);
        for (int i = 0; i < count; ++i)
        {
            auto& row = rows[i];
            row.linear1 = Vector(jacobian[i].data());
            row.angular1 = Vector(jacobian[i].data() + 3);
            row.linear2 = Vector(jacobian[i].data() + 6);
            row.angular2 = Vector(jacobian[i].data() + 9);
            row.targetVelocity = target[i];
            // ODE's lambda is a force, Jolt's is an impulse. Compliance is
            // divided by dt, force bounds multiplied by dt; friction bounds
            // are dimensionless multiples of the normal impulse.
            row.softness = softness[i] / step;
            row.frictionRow = friction[i];
            R_ASSERT2(row.frictionRow == -1 || (row.frictionRow >= 0 && row.frictionRow < i),
                "Invalid friction row dependency");
            row.lower = lower[i] * (friction[i] < 0 ? step : 1);
            row.upper = upper[i] * (friction[i] < 0 ? step : 1);
        }
    }

    JPH::EConstraintSubType GetSubType() const override { return JPH::EConstraintSubType::User1; }
    JPH::Mat44 GetConstraintToBody1Matrix() const override { return JPH::Mat44::sIdentity(); }
    JPH::Mat44 GetConstraintToBody2Matrix() const override { return JPH::Mat44::sIdentity(); }
    JPH::Ref<JPH::ConstraintSettings> GetConstraintSettings() const override { return nullptr; }
    void NotifyShapeChanged(const JPH::BodyID&, JPH::Vec3Arg) override {}
    void ResetWarmStart() override
    {
        for (auto& row : rows)
            row.impulse = 0;
    }

    void SetupVelocityConstraint(float) override
    {
        for (int i = 0; i < count; ++i)
        {
            auto& row = rows[i];
            Prepare(*mBody1, row.linear1, row.angular1, row.deltaLinear1, row.deltaAngular1);
            Prepare(*mBody2, row.linear2, row.angular2, row.deltaLinear2, row.deltaAngular2);
            const float inverseMass = row.linear1.Dot(row.deltaLinear1) + row.angular1.Dot(row.deltaAngular1)
                + row.linear2.Dot(row.deltaLinear2) + row.angular2.Dot(row.deltaAngular2) + row.softness;
            row.effectiveMass = inverseMass > 0 ? 1 / inverseMass : 0;
        }
    }

    // Engine contacts are rebuilt each step. Start at zero for both contacts
    // and persistent joints, matching the existing non-warm-starting solver.
    void WarmStartVelocityConstraint(float) override {}

    bool SolveVelocityConstraint(float) override
    {
        bool changed = false;
        for (int i = 0; i < count; ++i)
        {
            auto& row = rows[i];
            const float velocity = row.linear1.Dot(mBody1->GetLinearVelocity()) + row.angular1.Dot(mBody1->GetAngularVelocity())
                + row.linear2.Dot(mBody2->GetLinearVelocity()) + row.angular2.Dot(mBody2->GetAngularVelocity());
            float lower = row.lower;
            float upper = row.upper;
            if (row.frictionRow >= 0)
            {
                const float normalImpulse = std::abs(rows[row.frictionRow].impulse);
                upper = normalImpulse > 0 ? std::abs(row.upper) * normalImpulse : 0.f;
                lower = -upper;
            }
            const float proposed = row.impulse + row.effectiveMass * (row.targetVelocity - velocity - row.softness * row.impulse);
            const float impulse = std::clamp(proposed, lower, upper);
            const float difference = impulse - row.impulse;
            row.impulse = impulse;
            if (difference != 0)
            {
                Apply(*mBody1, row.deltaLinear1, row.deltaAngular1, difference);
                Apply(*mBody2, row.deltaLinear2, row.deltaAngular2, difference);
                changed = true;
            }
        }
        return changed;
    }

    // Position error is already represented by the engine's ERP velocity
    // target. Applying a second Baumgarte correction would over-correct it.
    bool SolvePositionConstraint(float, float) override { return false; }

    void Publish(float step)
    {
        std::fill(std::begin(source.lambda), std::end(source.lambda), 0.f);
        JPH::Vec3 force1 = JPH::Vec3::sZero(), torque1 = force1, force2 = force1, torque2 = force1;
        for (int i = 0; i < count; ++i)
        {
            const auto& row = rows[i];
            const float force = row.impulse / step;
            source.lambda[i] = force;
            force1 += row.linear1 * force;
            torque1 += row.angular1 * force;
            force2 += row.linear2 * force;
            torque2 += row.angular2 * force;
        }
        if (source.feedback)
        {
            Store(force1, source.feedback->f1);
            Store(torque1, source.feedback->t1);
            Store(force2, source.feedback->f2);
            Store(torque2, source.feedback->t2);
        }
    }

private:
    static void Prepare(const JPH::Body& body, JPH::Vec3Arg linear, JPH::Vec3Arg angular,
        JPH::Vec3& deltaLinear, JPH::Vec3& deltaAngular)
    {
        deltaLinear = deltaAngular = JPH::Vec3::sZero();
        if (body.IsDynamic())
        {
            const auto* motion = body.GetMotionProperties();
            deltaLinear = linear * motion->GetInverseMass();
            deltaAngular = motion->MultiplyWorldSpaceInverseInertiaByVector(body.GetRotation(), angular);
        }
    }

    static void Apply(JPH::Body& body, JPH::Vec3Arg linear, JPH::Vec3Arg angular, float impulse)
    {
        if (body.IsDynamic())
        {
            auto* motion = body.GetMotionProperties();
            motion->AddLinearVelocityStep(linear * impulse);
            motion->AddAngularVelocityStep(angular * impulse);
        }
    }

    dxJoint& source;
    std::array<Row, 6> rows;
    int count = 0;
};
}

class JoltDynamicsWorld::Impl
{
public:
    explicit Impl(unsigned workerThreads)
        : allocator(16 * 1024 * 1024), jobs(JPH::cMaxPhysicsJobs, JPH::cMaxPhysicsBarriers, workerThreads)
    {
        system.Init(65536, 0, 1, 1, broadPhaseLayers, broadPhaseFilter, pairFilter);
        shape = new JPH::SphereShape(.1f);
    }

    ~Impl()
    {
        ClearConstraints();
        auto& interface = system.GetBodyInterface();
        for (const auto& [source, body] : bodies)
        {
            interface.RemoveBody(body->GetID());
            interface.DestroyBody(body->GetID());
        }
    }

    void Step(std::span<CPHIsland* const> islands, float step, unsigned iterations)
    {
        R_ASSERT2(std::isfinite(step) && step > 0, "Invalid Jolt physics step");
        ClearConstraints();
        std::vector<dxBody*> sources;
        std::vector<dxJoint*> joints;
        for (auto* island : islands)
        {
            if (!island->IsActive())
                continue;
            for (auto* body = island->firstbody; body; body = static_cast<dxBody*>(body->next))
                sources.push_back(body);
            for (auto* joint = island->firstjoint; joint; joint = static_cast<dxJoint*>(joint->next))
                joints.push_back(joint);
        }
        const std::unordered_set<dxBody*> present(sources.begin(), sources.end());
        R_ASSERT2(present.size() == sources.size(), "Duplicate active island bodies");
        auto& interface = system.GetBodyInterface();
        for (auto it = bodies.begin(); it != bodies.end();)
        {
            if (!present.contains(it->first))
            {
                interface.RemoveBody(it->second->GetID());
                interface.DestroyBody(it->second->GetID());
                it = bodies.erase(it);
            }
            else
                ++it;
        }
        if (sources.empty())
            return;

        for (auto* source : sources)
        {
            const JPH::RVec3 position(source->posr.pos[0], source->posr.pos[1], source->posr.pos[2]);
            const JPH::Quat rotation(source->q[1], source->q[2], source->q[3], source->q[0]);
            auto it = bodies.find(source);
            if (it == bodies.end())
            {
                JPH::BodyCreationSettings settings(shape, position, rotation, JPH::EMotionType::Dynamic, 0);
                settings.mOverrideMassProperties = JPH::EOverrideMassProperties::MassAndInertiaProvided;
                settings.mMassPropertiesOverride = Mass(*source);
                settings.mAllowSleeping = false; // xrPhysics owns disabling and freeze state.
                settings.mLinearDamping = settings.mAngularDamping = 0; // Game code applies its own air resistance.
                // Jolt squares these limits on worker threads with floating
                // point exceptions enabled. Keep the square representable.
                settings.mMaxLinearVelocity = settings.mMaxAngularVelocity = 1.e10f;
                settings.mApplyGyroscopicForce = true;
                auto* body = interface.CreateBody(settings);
                R_ASSERT2(body, "Jolt physics body capacity exceeded");
                interface.AddBody(body->GetID(), JPH::EActivation::Activate);
                it = bodies.emplace(source, body).first;
            }
            auto* body = it->second;
            interface.SetPositionAndRotation(body->GetID(), position, rotation, JPH::EActivation::Activate);
            interface.SetLinearAndAngularVelocity(body->GetID(), Vector(source->lvel), Vector(source->avel));
            body->GetMotionProperties()->SetMassProperties(JPH::EAllowedDOFs::All, Mass(*source));
            body->GetMotionProperties()->SetGravityFactor(source->flags & dxBodyNoGravity ? 0.f : 1.f);
        }

        for (auto* source : joints)
        {
            // Detached joints do not contribute. All connected bodies must
            // belong to the submitted active islands (a merged engine island).
            if (!source->node[0].body)
                continue;
            auto& first = *bodies.at(source->node[0].body);
            auto& second = source->node[1].body ? *bodies.at(source->node[1].body) : JPH::Body::sFixedToWorld;
            JPH::Ref<JointConstraint> constraint = new JointConstraint(first, second, *source, step);
            system.AddConstraint(constraint);
            constraints.push_back(constraint);
        }
        // Joint row generation can itself add motor/limit forces. Copy them
        // only after every getInfo2 call has completed.
        for (auto* source : sources)
        {
            auto* body = bodies.at(source);
            body->AddForce(Vector(source->facc));
            body->AddTorque(Vector(source->tacc));
        }
        dVector3 gravity;
        dWorldGetGravity(sources.front()->world, gravity);
        system.SetGravity(Vector(gravity));
        auto settings = system.GetPhysicsSettings();
        settings.mNumVelocitySteps = std::max(1u, iterations);
        settings.mNumPositionSteps = 1;
        system.SetPhysicsSettings(settings);
        const auto error = system.Update(step, 1, &allocator, &jobs);
        R_ASSERT2(error == JPH::EPhysicsUpdateError::None, "Jolt physics update failed");

        for (auto* source : sources)
        {
            auto* body = bodies.at(source);
            const auto position = body->GetPosition();
            const auto rotation = body->GetRotation();
            dQuaternion quaternion{ rotation.GetW(), rotation.GetX(), rotation.GetY(), rotation.GetZ() };
            if (!(source->flags & dxBodyNoUpdatePos))
            {
                dBodySetPosition(source, position.GetX(), position.GetY(), position.GetZ());
                dBodySetQuaternion(source, quaternion); // Updates R and invalidates geometry bounds.
            }
            Store(body->GetLinearVelocity(), source->lvel);
            Store(body->GetAngularVelocity(), source->avel);
            std::fill(std::begin(source->facc), std::end(source->facc), 0.f);
            std::fill(std::begin(source->tacc), std::end(source->tacc), 0.f);
        }
        for (auto& constraint : constraints)
            constraint->Publish(step);
        ClearConstraints(); // Never retain references to temporary engine contacts.
    }

private:
    void ClearConstraints()
    {
        for (auto& constraint : constraints)
            system.RemoveConstraint(constraint);
        constraints.clear();
    }

    BroadPhaseLayers broadPhaseLayers;
    ObjectBroadPhaseFilter broadPhaseFilter;
    ObjectPairFilter pairFilter;
    JPH::TempAllocatorImpl allocator;
    JPH::JobSystemThreadPool jobs;
    JPH::PhysicsSystem system;
    JPH::RefConst<JPH::Shape> shape;
    std::unordered_map<dxBody*, JPH::Body*> bodies;
    std::vector<JPH::Ref<JointConstraint>> constraints;
};

JoltDynamicsWorld::JoltDynamicsWorld(unsigned workerThreads)
{
    // Register before constructing members that can allocate through Jolt.
    static JoltRuntime runtime;
    impl = std::make_unique<Impl>(workerThreads);
}
JoltDynamicsWorld::~JoltDynamicsWorld() = default;
void JoltDynamicsWorld::Step(std::span<CPHIsland* const> islands, float step, unsigned iterations)
{
    impl->Step(islands, step, iterations);
}
