# HTTP SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=ghttpc

PROG_OBJS = \
	../../../md5c.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../common/gsAssert.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsCrypt.o\
	../../../common/gsLargeInt.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsMemory.o\
	../../../common/gsXML.o\
	../../../common/gsSHA1.o\
	../../../common/gsRC4.o\
	../../../common/gsSSL.o\
	../../ghttpBuffer.o\
	../../ghttpCallbacks.o\
	../../ghttpConnection.o\
	../../ghttpEncryption.o\
	../../ghttpMain.o\
	../../ghttpProcess.o\
	../../ghttpCommon.o\
	../../ghttpPost.o\
	../ghttpc.o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
