// Android-only, line-scoped rewrites for desktop-oriented OpenXRay GLSL.
//
// Rules are scoped to their virtual shader path. Game and mod assets remain
// untouched, while overrides of the same PC shader receive the same fix.
XR_GLES_LINE_REWRITE("accum_sun_far.ps", "gbuffer_data gbd = gbuffer_load_data( GLD_P(I.tc, I.hpos, ISAMPLE) );", "gbuffer_data gbd = gbuffer_load_data( GLD_P(I.tc.xy, I.hpos, ISAMPLE) );")
XR_GLES_LINE_REWRITE("accum_sun_far.ps", "return s;", "return float4(s);")
XR_GLES_LINE_REWRITE("accum_sun_far.ps", "tc_f \t*= step( -dot( tc_f, view_shadow_proj.xy ), 0 );", "tc_f \t*= step( -dot( tc_f, view_shadow_proj.xy ), 0.0 );")
XR_GLES_LINE_REWRITE("accum_sun_near.ps", "gbuffer_data gbd = gbuffer_load_data( GLD_P(I.tc, I.hpos, ISAMPLE) );", "gbuffer_data gbd = gbuffer_load_data( GLD_P(I.tc.xy, I.hpos, ISAMPLE) );")
XR_GLES_LINE_REWRITE("accum_sun_near.ps", "return s;", "return float4(s);")
XR_GLES_LINE_REWRITE("accum_volumetric.ps", "float  att \t= saturate( 1 - rsqr * Ldynamic_pos.w ); // q-linear attenuate", "float  att \t= saturate( 1.0 - rsqr * Ldynamic_pos.w ); // q-linear attenuate")
XR_GLES_LINE_REWRITE("accum_volumetric.ps", "return  float4( result, 0);", "return  float4(result, 0.0);")
XR_GLES_LINE_REWRITE("accum_volumetric.vs", "vPos.w \t\t= 1;", "vPos.w \t\t= 1.0;")
XR_GLES_LINE_REWRITE("accum_volumetric_sun.ps", "float\tcoeff = (RAY_SAMPLES - 1.0*J0.x)/(RAY_SAMPLES*RAY_SAMPLES);", "float\tcoeff = (float(RAY_SAMPLES) - J0.x) / (float(RAY_SAMPLES) * float(RAY_SAMPLES));")
XR_GLES_LINE_REWRITE("bloom_filter_f.ps", "return  ( (t_0+t_1) + (t_2+t_3) ) / 2;", "return  ( (t_0+t_1) + (t_2+t_3) ) / 2.0;")
XR_GLES_LINE_REWRITE("clouds.vs", "float2  d0\t= v.dir.xy*2-1;", "float2  d0\t= v.dir.xy * 2.0 - 1.0;")
XR_GLES_LINE_REWRITE("clouds.vs", "float2  d1\t= v.dir.wz*2-1;", "float2  d1\t= v.dir.wz * 2.0 - 1.0;")
XR_GLES_LINE_REWRITE("clouds.vs", "float2 \t_0\t= v.p.xz * CLOUD_TILE0 + d0*timers.z*CLOUD_SPEED0;", "float2 \t_0\t= v.p.xz * CLOUD_TILE0 + d0 * timers.z * float(CLOUD_SPEED0);")
XR_GLES_LINE_REWRITE("clouds.vs", "float2 \t_1\t= v.p.xz * CLOUD_TILE1 + d1*timers.z*CLOUD_SPEED1;", "float2 \t_1\t= v.p.xz * CLOUD_TILE1 + d1 * timers.z * float(CLOUD_SPEED1);")
XR_GLES_LINE_REWRITE("clouds.vs", "o.color.w\t*= \tpow\t\t(v.p.y,25);", "o.color.w\t*= \tpow\t\t(v.p.y, 25.0);")
XR_GLES_LINE_REWRITE("combine_1.ps", "float sun_occ = P.w*2;", "float sun_occ = P.w * 2.0;")
XR_GLES_LINE_REWRITE("combine_2_aa.ps", "nd \t\t=  step\t\t(0,nd);\t// bw", "nd \t\t=  step\t\t(float4(0.0), nd);\t// bw")
XR_GLES_LINE_REWRITE("combine_2_aa.ps", "dd \t\t=  abs(2*dc.z-dd)-e_barrier.y;", "dd \t\t=  abs(2.0 * dc.z - dd) - e_barrier.y;")
XR_GLES_LINE_REWRITE("combine_2_aa.ps", "dd \t\t=  step\t\t(dd,int4(0));\t\t// bw", "dd \t\t=  step\t\t(dd, float4(0.0));\t\t// bw")
XR_GLES_LINE_REWRITE("combine_2_aa.ps", "float2\toffset \t=  center * (1-w);", "float2\toffset \t=  center * (1.0 - w);")
XR_GLES_LINE_REWRITE("deffer_base_aref_bump.ps", "S.base.w = (S.base.w-def_aref*0.5)/(1-def_aref*0.5);", "S.base.w = (S.base.w - def_aref * 0.5) / (1.0 - def_aref * 0.5);")
XR_GLES_LINE_REWRITE("deffer_base_aref_flat.ps", "D.w = (D.w-def_aref*0.5)/(1-def_aref*0.5);", "D.w = (D.w - def_aref * 0.5) / (1.0 - def_aref * 0.5);")
XR_GLES_LINE_REWRITE("deffer_base_aref_flat.ps", "D.rgb\t= 2*D.rgb*tex2D\t(s_detail, I.tcdbump).rgb;", "D.rgb\t= 2.0 * D.rgb * tex2D(s_detail, I.tcdbump).rgb;")
XR_GLES_LINE_REWRITE("deffer_base_flat.ps", "D.rgb\t= 2*D.rgb*tex2D\t(s_detail, I.tcdbump).rgb;", "D.rgb\t= 2.0 * D.rgb * tex2D(s_detail, I.tcdbump).rgb;")
XR_GLES_LINE_REWRITE("deffer_detail_s_flat.vs", "pos.w \t\t= 1;", "pos.w \t\t= 1.0;")
XR_GLES_LINE_REWRITE("deffer_detail_w_flat.vs", "pos.w \t\t= 1;", "pos.w \t\t= 1.0;")
XR_GLES_LINE_REWRITE("deffer_impl_flat.ps", "D.rgb\t= 2*D.rgb*dt.rgb\t ;", "D.rgb\t= 2.0 * D.rgb * dt.rgb;")
XR_GLES_LINE_REWRITE("depth_downs.ps", "gbuffer_data gbd0 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5f * pos_decompression_params2.zw, I.pos2d * 2, ISAMPLE) );", "gbuffer_data gbd0 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5f * pos_decompression_params2.zw, I.pos2d * 2.0, ISAMPLE) );")
XR_GLES_LINE_REWRITE("depth_downs.ps", "gbuffer_data gbd1 = gbuffer_load_data( GLD_P(I.tc0.xy - 0.5f * pos_decompression_params2.zw, I.pos2d * 2, ISAMPLE) );", "gbuffer_data gbd1 = gbuffer_load_data( GLD_P(I.tc0.xy - 0.5f * pos_decompression_params2.zw, I.pos2d * 2.0, ISAMPLE) );")
XR_GLES_LINE_REWRITE("depth_downs.ps", "gbuffer_data gbd2 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5f * float2(+pos_decompression_params2.z, -pos_decompression_params2.w), I.pos2d * 2, ISAMPLE) );", "gbuffer_data gbd2 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5f * float2(+pos_decompression_params2.z, -pos_decompression_params2.w), I.pos2d * 2.0, ISAMPLE) );")
XR_GLES_LINE_REWRITE("depth_downs.ps", "gbuffer_data gbd3 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5f * float2(-pos_decompression_params2.z, +pos_decompression_params2.w), I.pos2d * 2, ISAMPLE) );", "gbuffer_data gbd3 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5f * float2(-pos_decompression_params2.z, +pos_decompression_params2.w), I.pos2d * 2.0, ISAMPLE) );")
XR_GLES_LINE_REWRITE("gather.ps", "float s0 = textureLodOffset( s_dmap, rcp_scale * offset + tc, 0, int2( 0, 1 ) ).x;", "float s0 = textureLodOffset( s_dmap, rcp_scale * float2(offset) + tc, 0.0, int2( 0, 1 ) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s1 = textureLodOffset( s_dmap, rcp_scale * offset + tc, 0, int2( 1, 1 ) ).x;", "float s1 = textureLodOffset( s_dmap, rcp_scale * float2(offset) + tc, 0.0, int2( 1, 1 ) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s2 = textureLodOffset( s_dmap, rcp_scale * offset + tc, 0, int2( 1, 0 ) ).x;", "float s2 = textureLodOffset( s_dmap, rcp_scale * float2(offset) + tc, 0.0, int2( 1, 0 ) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s3 = textureLodOffset( s_dmap, rcp_scale * offset + tc, 0, int2( 0, 0 ) ).x;", "float s3 = textureLodOffset( s_dmap, rcp_scale * float2(offset) + tc, 0.0, int2( 0, 0 ) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s0 = textureLodOffset( s_smap_minmax, rcp_scale * offset + tc, 0, int2(0, 1) ).x;", "float s0 = textureLodOffset( s_smap_minmax, rcp_scale * float2(offset) + tc, 0.0, int2(0, 1) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s1 = textureLodOffset( s_smap_minmax, rcp_scale * offset + tc, 0, int2(1, 1) ).x;", "float s1 = textureLodOffset( s_smap_minmax, rcp_scale * float2(offset) + tc, 0.0, int2(1, 1) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s2 = textureLodOffset( s_smap_minmax, rcp_scale * offset + tc, 0, int2(1, 0) ).x;", "float s2 = textureLodOffset( s_smap_minmax, rcp_scale * float2(offset) + tc, 0.0, int2(1, 0) ).x;")
XR_GLES_LINE_REWRITE("gather.ps", "float s3 = textureLodOffset( s_smap_minmax, rcp_scale * offset + tc, 0, int2(0, 0) ).x;", "float s3 = textureLodOffset( s_smap_minmax, rcp_scale * float2(offset) + tc, 0.0, int2(0, 0) ).x;")
XR_GLES_LINE_REWRITE("hmodel.h", "float4\tlight\t= textureLod(s_material, float3( hscale, hspec, m ), 0 ).xxxy;", "float4\tlight\t= textureLod(s_material, float3( hscale, hspec, m ), 0.0 ).xxxy;")
XR_GLES_LINE_REWRITE("hmodel.h", "float3\te0d\t\t= textureLod( env_s0, nw, 0 ).rgb;", "float3\te0d\t\t= textureLod( env_s0, nw, 0.0 ).rgb;")
XR_GLES_LINE_REWRITE("hmodel.h", "float3\te1d\t\t= textureLod( env_s1, nw, 0 ).rgb;", "float3\te1d\t\t= textureLod( env_s1, nw, 0.0 ).rgb;")
XR_GLES_LINE_REWRITE("hmodel.h", "vreflect.y      = vreflect.y*2-1;\t// fake remapping", "vreflect.y      = vreflect.y * 2.0 - 1.0;\t// fake remapping")
XR_GLES_LINE_REWRITE("hmodel.h", "float3\te0s\t\t= textureLod( env_s0, vreflect, 0 ).rgb;", "float3\te0s\t\t= textureLod( env_s0, vreflect, 0.0 ).rgb;")
XR_GLES_LINE_REWRITE("hmodel.h", "float3\te1s\t\t= textureLod( env_s1, vreflect, 0 ).rgb;", "float3\te1s\t\t= textureLod( env_s1, vreflect, 0.0 ).rgb;")
XR_GLES_LINE_REWRITE("hud3d.vs", "O.HPos.w\t= 1;", "O.HPos.w\t= 1.0;")
XR_GLES_LINE_REWRITE("iostructs/v_model_bump.h", "I.N = v_model_N;", "I.N = skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_bump.h", "I.T = v_model_T;", "I.T = skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_bump.h", "I.B = v_model_B;", "I.B = skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_bump.h", "I.tc = v_model_tc;", "I.tc = skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def.h", "I.N = v_model_N;", "I.N = skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def.h", "I.T = v_model_T;", "I.T = skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def.h", "I.B = v_model_B;", "I.B = skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def.h", "I.tc = v_model_tc;", "I.tc = skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def_lplanes.h", "I.N\t\t= v_model_N;", "I.N\t\t= skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def_lplanes.h", "I.T\t\t= v_model_T;", "I.T\t\t= skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def_lplanes.h", "I.B\t\t= v_model_B;", "I.B\t\t= skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_def_lplanes.h", "I.tc\t\t= v_model_tc;", "I.tc\t\t= skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_distort.h", "I.N = v_model_N;", "I.N = skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_distort.h", "I.T = v_model_T;", "I.T = skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_distort.h", "I.B = v_model_B;", "I.B = skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_distort.h", "I.tc = v_model_tc;", "I.tc = skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_env_lq.h", "I.N\t\t= v_model_N;", "I.N\t\t= skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_env_lq.h", "I.T\t\t= v_model_T;", "I.T\t\t= skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_env_lq.h", "I.B\t\t= v_model_B;", "I.B\t\t= skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_env_lq.h", "I.tc\t\t= v_model_tc;", "I.tc\t\t= skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_flat.h", "I.N = v_model_N;", "I.N = skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_flat.h", "I.T = v_model_T;", "I.T = skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_flat.h", "I.B = v_model_B;", "I.B = skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_flat.h", "I.tc = v_model_tc;", "I.tc = skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow.h", "I.N = v_model_N;", "I.N = skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow.h", "I.T = v_model_T;", "I.T = skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow.h", "I.B = v_model_B;", "I.B = skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow.h", "I.tc = v_model_tc;", "I.tc = skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow_aref.h", "I.N = v_model_N;", "I.N = skin_input_normal(v_model_N);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow_aref.h", "I.T = v_model_T;", "I.T = skin_input_tangent(v_model_T);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow_aref.h", "I.B = v_model_B;", "I.B = skin_input_tangent(v_model_B);")
XR_GLES_LINE_REWRITE("iostructs/v_model_shadow_aref.h", "I.tc = v_model_tc;", "I.tc = skin_input_tc(v_model_tc);")
XR_GLES_LINE_REWRITE("lmodel.h", "float  att \t= saturate\t(1 - rsqr*light_range_rsq);\t\t\t// q-linear attenuate", "float  att \t= saturate\t(1.0 - rsqr*light_range_rsq);\t\t\t// q-linear attenuate")
XR_GLES_LINE_REWRITE("model_def_lq.ps", "float3\tfinal \t= light*t_base.rgb*2;", "float3\tfinal \t= light * t_base.rgb * 2.0;")
XR_GLES_LINE_REWRITE("postprocess.ps", "image\t= (image * I.Color.rgb + c_brightness.rgb)*2;\t\t// mad", "image\t= (image * I.Color.rgb + c_brightness.rgb) * 2.0;\t\t// mad")
XR_GLES_LINE_REWRITE("postprocess_cm.ps", "image\t= (image * I.Color.rgb + c_brightness.rgb)*2;\t\t// mad", "image\t= (image * I.Color.rgb + c_brightness.rgb) * 2.0;\t\t// mad")
XR_GLES_LINE_REWRITE("rain_layer.ps", "float4 water = textureLod( s_water, tc1, 0 );", "float4 water = textureLod( s_water, tc1, 0.0 );")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "water.y = 0;", "water.y = 0.0;")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "float\tfAtten = 1 - smoothstep( 5, 20, _P.z );", "float\tfAtten = 1.0 - smoothstep( 5.0, 20.0, _P.z );")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "s *= saturate(fIsUp*10+(10*0.5)+0.5);", "s *= saturate(fIsUp * 10.0 + (10.0 * 0.5) + 0.5);")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "fIsUp = max(0, fIsUp);", "fIsUp = max(0.0, fIsUp);")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "float3 tc1 = WorldP / 2;", "float3 tc1 = WorldP / 2.0;")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "float fAngleFactor = 1 - fIsUp;", "float fAngleFactor = 1.0 - fIsUp;")
XR_GLES_LINE_REWRITE("rain_patch_normal.ps", "fAngleFactor = 0.1*ceil(10*fAngleFactor);", "fAngleFactor = 0.1 * ceil(10.0 * fAngleFactor);")
XR_GLES_LINE_REWRITE("shadow.h", "d4.w = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col, row ), 0 ).x;", "d4.w = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col, row ), 0.0 ).x;")
XR_GLES_LINE_REWRITE("shadow.h", "d4.z = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col+1, row ) , 0 ).x;", "d4.z = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col+1, row ) , 0.0 ).x;")
XR_GLES_LINE_REWRITE("shadow.h", "d4.y = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col+1, row+1 ), 0 ).x;", "d4.y = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col+1, row+1 ), 0.0 ).x;")
XR_GLES_LINE_REWRITE("shadow.h", "d4.x = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col, row+1 ), 0 ).x;", "d4.x = textureLod( s_dmap, tc.xy + (1.0/float(SMAP_size)) * float2( col, row+1 ), 0.0 ).x;")
XR_GLES_LINE_REWRITE("shadow.h", "r1.x \t= test \t(tc,-J0.xy+half2(-k1,0)).x;", "r1.x \t= test \t(tc,-J0.xy+half2(-k1,0.0)).x;")
XR_GLES_LINE_REWRITE("shadow.h", "r1.y \t= test \t(tc,-J0.wz+half2( 0,-k1)).y;", "r1.y \t= test \t(tc,-J0.wz+half2( 0.0,-k1)).y;")
XR_GLES_LINE_REWRITE("shadow.h", "r1.z\t= test\t(tc,-2*J0.xy+half2( k1, 0)).z;", "r1.z\t= test\t(tc,-2.0*J0.xy+half2( k1, 0.0)).z;")
XR_GLES_LINE_REWRITE("shadow.h", "r1.w\t= test\t(tc,-2*J0.wz+half2( 0, k1)).x;", "r1.w\t= test\t(tc,-2.0*J0.wz+half2( 0.0, k1)).x;")
XR_GLES_LINE_REWRITE("shadow.h", "float minmax     = textureLod( s_smap_minmax, t.xy, 0 ).x;", "float minmax     = textureLod( s_smap_minmax, t.xy, 0.0 ).x;")
XR_GLES_LINE_REWRITE("shadow.h", "bool   umbra     = ( ( minmax < 0 ) && ( t.z > -minmax ) );", "bool   umbra     = ( ( minmax < 0.0 ) && ( t.z > -minmax ) );")
XR_GLES_LINE_REWRITE("shadow_direct_tree.vs", "float \tfrac \t= 0;", "float \tfrac \t= 0.0;")
XR_GLES_LINE_REWRITE("shadow_direct_base.vs", "O.depth = O.hpos.z;", "")
XR_GLES_LINE_REWRITE("shadow_direct_base_aref.vs", "O.depth = O.hpos.z;", "")
XR_GLES_LINE_REWRITE("shadow_direct_model.vs", "O.depth \t\t= O.hpos.z;", "")
XR_GLES_LINE_REWRITE("shadow_direct_model_aref.vs", "O.depth = O.hpos.z;", "")
XR_GLES_LINE_REWRITE("shadow_direct_tree.vs", "O.depth = O.hpos.z;", "")
XR_GLES_LINE_REWRITE("shadow_direct_base_aref.ps", "return I.depth;", "return C;")
XR_GLES_LINE_REWRITE("shared/cloudconfig.h", "#define CLOUD_SPEED0\t\t(2*0.05)\t\t//(0.033)", "#define CLOUD_SPEED0\t\t(2.0*0.05)\t\t//(0.033)")
XR_GLES_LINE_REWRITE("shared/cloudconfig.h", "#define CLOUD_SPEED1\t\t(2*0.025)\t\t//(0.033)", "#define CLOUD_SPEED1\t\t(2.0*0.025)\t\t//(0.033)")
XR_GLES_LINE_REWRITE("shared/common.h", "#define clip(x)\t\tif (x < 0) discard", "#define clip(x)\t\tif ((x) < 0.0) discard")
XR_GLES_LINE_REWRITE("shared/watermove.h", "amount\t= 1 - fresnel*fresnel;\t\t\t// 0=full env, 1=no env", "amount\t= 1.0 - fresnel * fresnel;\t\t\t// 0=full env, 1=no env")
XR_GLES_LINE_REWRITE("skin.h", "int \tmid = int(v.N.w * 255 + 0.3);", "int \tmid = int(v.N.w * 255.0 + 0.3);")
XR_GLES_LINE_REWRITE("skin.h", "int \tid_2 \t= int(v.B.w*255+0.3);", "int \tid_2 \t= int(v.B.w * 255.0 + 0.3);")
XR_GLES_LINE_REWRITE("skin.h", "float \tw2 \t= 1-w0-w1;", "float \tw2 \t= 1.0 - w0 - w1;")
XR_GLES_LINE_REWRITE("skin.h", "id[i] = int(v.ind[i]*255+0.3);", "id[i] = int(v.ind[i] * 255.0 + 0.3);")
XR_GLES_LINE_REWRITE("skin.h", "w[3]\t= 1-w[0]-w[1]-w[2];", "w[3]\t= 1.0 - w[0] - w[1] - w[2];")
XR_GLES_LINE_REWRITE("sload.h", "const float maxSamples = 25;", "const float maxSamples = 25.0;")
XR_GLES_LINE_REWRITE("sload.h", "const float minSamples = 5;", "const float minSamples = 5.0;")
XR_GLES_LINE_REWRITE("sload.h", "float2\tvTexCurrentOffset\t= I.tcdh;", "float2\tvTexCurrentOffset\t= I.tcdh.xy;")
XR_GLES_LINE_REWRITE("sload.h", "for( int i=0; i<nNumSteps; ++i )", "for( int i=0; float(i) < nNumSteps; ++i )")
XR_GLES_LINE_REWRITE("sload.h", "fCurrHeight = textureLod( s_bumpX, vTexCurrentOffset.xy, 0 ).a;", "fCurrHeight = textureLod( s_bumpX, vTexCurrentOffset.xy, 0.0 ).a;")
XR_GLES_LINE_REWRITE("sload.h", "float fPrevHeight = textureLod( s_bumpX, vTexCurrentOffset.xy, 0 ).a;", "float fPrevHeight = textureLod( s_bumpX, vTexCurrentOffset.xy, 0.0 ).a;")
XR_GLES_LINE_REWRITE("sload.h", "float2\tvParallaxOffset = vDelta * ((1- fParallaxAmount )*fParallaxFade);", "float2\tvParallaxOffset = vDelta * ((1.0 - fParallaxAmount) * fParallaxFade);")
XR_GLES_LINE_REWRITE("sload.h", "float2\tvTexCoord = I.tcdh + vParallaxOffset;", "float2\tvTexCoord = I.tcdh.xy + vParallaxOffset;")
XR_GLES_LINE_REWRITE("sload.h", "I.tcdh = vTexCoord;", "I.tcdh.xy = vTexCoord;")
XR_GLES_LINE_REWRITE("sload.h", "float\theight\t= tex2D( s_bumpX, I.tcdh ).w;\t//", "float\theight\t= tex2D( s_bumpX, I.tcdh.xy ).w;\t//")
XR_GLES_LINE_REWRITE("sload.h", "float2\tnew_tc  = I.tcdh + height * normalize(eye).xy;\t//", "float2\tnew_tc  = I.tcdh.xy + height * normalize(eye).xy;\t//")
XR_GLES_LINE_REWRITE("sload.h", "I.tcdh\t= new_tc;", "I.tcdh.xy = new_tc;")
XR_GLES_LINE_REWRITE("sload.h", "float4 \tNu\t= tex2D( s_bump, I.tcdh );\t\t// IN:\tnormal.gloss", "float4 \tNu\t= tex2D( s_bump, I.tcdh.xy );\t\t// IN:\tnormal.gloss")
XR_GLES_LINE_REWRITE("sload.h", "float4 \tNuE\t= tex2D( s_bumpX, I.tcdh);\t\t// IN:\tnormal_error.height", "float4 \tNuE\t= tex2D( s_bumpX, I.tcdh.xy);\t\t// IN:\tnormal_error.height")
XR_GLES_LINE_REWRITE("sload.h", "S.base\t\t= tbase(I.tcdh);\t\t\t\t//\tIN:  rgb.a", "S.base\t\t= tbase(I.tcdh.xy);\t\t\t\t//\tIN:  rgb.a")
XR_GLES_LINE_REWRITE("sload.h", "S.base.rgb\t\t\t= S.base.rgb * detail.rgb * 2;", "S.base.rgb\t\t\t= S.base.rgb * detail.rgb * 2.0;")
XR_GLES_LINE_REWRITE("sload.h", "float4 \tNuE\t= tex2D( s_bumpX, I.tcdh);\t// IN:\tnormal_error.height", "float4 \tNuE\t= tex2D( s_bumpX, I.tcdh.xy);\t// IN:\tnormal_error.height")
XR_GLES_LINE_REWRITE("sload.h", "S.height = 0;", "S.height = 0.0;")
XR_GLES_LINE_REWRITE("ssao.ps", "float\tz\t= textureLod(s_half_depth,tap,0).r;", "float\tz\t= textureLod(s_half_depth,tap,0.0).r;")
XR_GLES_LINE_REWRITE("ssao.ps", "float\trange_att = saturate(1-dist*0.5);", "float\trange_att = saturate(1.0 - dist * 0.5);")
XR_GLES_LINE_REWRITE("ssao.ps", "occ += (infl+0.01)*lerp( 1, occ_factor, infl)*range_att;", "occ += (infl + 0.01) * lerp(1.0, occ_factor, infl) * range_att;")
XR_GLES_LINE_REWRITE("ssao.ps", "occ = (occ+0.3)/(1+0.3);", "occ = (occ + 0.3) / (1.0 + 0.3);")
XR_GLES_LINE_REWRITE("ssao.ps", "occ = (occ+0.2)/(1+0.2);", "occ = (occ + 0.2) / (1.0 + 0.2);")
XR_GLES_LINE_REWRITE("ssao.ps", "occ = lerp( 1, occ, WeaponAttenuation );", "occ = lerp(1.0, occ, WeaponAttenuation);")
XR_GLES_LINE_REWRITE("ssao_blur.ps", "float fDiff\t  = 8*abs(fDepth-centerDepth)/min(fDepth,centerDepth);", "float fDiff\t  = 8.0 * abs(fDepth - centerDepth) / min(fDepth, centerDepth);")
XR_GLES_LINE_REWRITE("ssao_blur.ps", "float fWeight = saturate(1-fDiff);", "float fWeight = saturate(1.0 - fDiff);")
XR_GLES_LINE_REWRITE("ssao_calc.ps", "gbuffer_data gbd0 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5 * pos_decompression_params2.zw, I.pos2d * 2, ISAMPLE) );", "gbuffer_data gbd0 = gbuffer_load_data( GLD_P(I.tc0.xy + 0.5 * pos_decompression_params2.zw, I.pos2d * 2.0, ISAMPLE) );")
XR_GLES_LINE_REWRITE("ssao_hbao.ps", "float z = textureLod( s_half_depth, uv, 0 ).z;", "float z = textureLod( s_half_depth, uv, 0.0 ).z;")
XR_GLES_LINE_REWRITE("ssao_hbao.ps", "float3 rand_Dir = textureLod(jitter4, tc1.xz, 0).xyz;", "float3 rand_Dir = textureLod(jitter4, tc1.xz, 0.0).xyz;")
XR_GLES_LINE_REWRITE("water.ps", "float\tpower\t= pow(fresnel,9);", "float\tpower\t= pow(fresnel, 9.0);")
XR_GLES_LINE_REWRITE("waterd.vs", "o.tbase\t\t= unpack_tc_base\t(v.uv,v.T.w,v.B.w);\t\t// copy tc", "o.tbase\t\t= unpack_tc_base\t(float2(v.uv), v.T.w, v.B.w);\t\t// copy tc")
