//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /nologo /Tps_2_0 /Emain /Zpr /Fctest\p20_deffer_impl_flat_d.ps
//    deffer_impl_flat_d.ps
//
//
// Parameters:
//
//   float4 L_material;
//   sampler2D s_base;
//   sampler2D s_dn_a;
//   sampler2D s_dn_b;
//   sampler2D s_dn_g;
//   sampler2D s_dn_r;
//   sampler2D s_dt_a;
//   sampler2D s_dt_b;
//   sampler2D s_dt_g;
//   sampler2D s_dt_r;
//   sampler2D s_mask;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   L_material   c0       1
//   s_base       s0       1
//   s_mask       s1       1
//   s_dt_r       s2       1
//   s_dt_g       s3       1
//   s_dt_b       s4       1
//   s_dt_a       s5       1
//   s_dn_r       s6       1
//   s_dn_g       s7       1
//   s_dn_b       s8       1
//   s_dn_a       s9       1
//

    ps_2_0
    def c1, 1, -0.5, 0.5, 0.0250000004
    def c2, 1, 1, 0.5, 0.00784313772
    dcl t0.xy
    dcl t1.xyz
    dcl_pp t2.xyz
    dcl_pp t3.xyz
    dcl_pp t4.xyz
    dcl t5.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s6
    dcl_2d s7
    dcl_2d s8
    dcl_2d s9
    texld_pp r9, t5, s9
    texld_pp r8, t5, s8
    texld_pp r7, t5, s6
    texld_pp r6, t5, s7
    texld_pp r2, t0, s1
    texld_pp r0, t0, s0
    texld_pp r5, t5, s3
    texld_pp r4, t5, s2
    texld_pp r3, t5, s4
    texld_pp r1, t5, s5
    add_pp r9.xyz, r9.wzyx, c1.y
    add_pp r8.xyz, r8.wzyx, c1.y
    add_pp r7.xyz, r7.wzyx, c1.y
    dp4_pp r1.w, r2, c1.x
    add_pp r6.xyz, r6.wzyx, c1.y
    rcp_pp r1.w, r1.w
    mul_pp r2, r2, r1.w
    mul_pp r6.xyz, r6, r2.y
    mad_pp r6.xyz, r7, r2.x, r6
    mad_pp r6.xyz, r8, r2.z, r6
    mad_pp r6.xyz, r9, r2.w, r6
    mul_pp r6.w, r6.z, c1.z
    mul r1.w, r6.x, t2.x
    mad r1.w, t2.y, r6.y, r1.w
    mad_pp r7.x, t2.z, r6.w, r1.w
    mul_pp r6.xyz, r6, c2
    dp3_pp r7.y, t3, r6
    dp3_pp r7.z, t4, r6
    nrm_pp r6.xyz, r7
    mad_pp r7.xyz, r6, c1.w, t1
    mov_pp r7.w, c0.w
    mov_pp oC0, r7
    mov_pp r6.w, r0.w
    mov_pp oC1, r6
    mul_pp r5.xyz, r5, r2.y
    mad_pp r4.xyz, r4, r2.x, r5
    mad_pp r2.xyz, r3, r2.z, r4
    mad_pp r1.xyz, r1, r2.w, r2
    mul_pp r0.xyz, r0, r1
    add_pp r0.xyz, r0, r0
    mov r0.w, c2.w
    mov_pp oC2, r0

// approximately 44 instruction slots used (10 texture, 34 arithmetic)
