//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /nologo /Tps_2_b /Emain /Zpr /Fctest\p2b_accum_sun_near.ps
//    accum_sun_near.ps
//
//
// Parameters:
//
//   float4 Ldynamic_color;
//   float4 Ldynamic_dir;
//   row_major float4x4 m_shadow;
//   row_major float3x4 m_sunmask;
//   sampler2D s_accumulator;
//   sampler2D s_lmap;
//   sampler3D s_material;
//   sampler2D s_normal;
//   sampler2D s_position;
//   sampler2D s_smap;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   m_shadow       c0       4
//   m_sunmask      c4       2
//   Ldynamic_color c6       1
//   Ldynamic_dir   c7       1
//   s_position     s0       1
//   s_normal       s1       1
//   s_smap         s2       1
//   s_lmap         s3       1
//   s_material     s4       1
//   s_accumulator  s5       1
//

    ps_2_x
    def c8, 1, -0.000537109387, -4.88281257e-005, 0
    def c9, -0.000537109387, -4.88281257e-005, 2048, 0.25
    def c10, 4.88281257e-005, -0.000537109387, 0, 0
    def c11, 0.000537109387, -0.000537109387, 0, 0
    def c12, -4.88281257e-005, -0.000537109387, 0, 0
    def c13, 4.88281257e-005, -4.88281257e-005, 0, 0
    def c14, 0.000537109387, -4.88281257e-005, 0, 0
    dcl t0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_volume s4
    dcl_2d s5
    texld r0, t0, s0
    texld_pp r1, t0, s1
    mov r19.xyz, r0
    mov r19.w, c8.x
    dp4 r1.w, c3, r19
    dp4 r0.x, c0, r19
    rcp r1.w, r1.w
    dp4 r0.y, c1, r19
    mad r14.xy, r0, r1.w, c9
    mad r13.xy, r0, r1.w, c12
    mad r3.xy, r0, r1.w, c8.z
    mad r23.xy, r0, r1.w, c8.y
    mad r12.xy, r0, r1.w, c13
    mad r11.xy, r0, r1.w, c11
    mad r10.xy, r0, r1.w, c14
    mad r22.xy, r0, r1.w, c10
    mad r9.xy, r0, r1.w, -c11
    mad r8.xy, r0, r1.w, -c13
    mad r7.xy, r0, r1.w, -c10
    mad r21.xy, r0, r1.w, -c14
    mad r6.xy, r0, r1.w, -c12
    mad r5.xy, r0, r1.w, -c9
    mad r4.xy, r0, r1.w, -c8.y
    mad r20.xy, r0, r1.w, -c8.z
    dp4 r24.x, c4, r19
    dp4 r24.y, c5, r19
    nrm_pp r2.xyz, r19
    dp3_pp r0.x, r2, r1
    mov_pp r0.z, r0.w
    add_pp r0.w, r0.x, r0.x
    mad_pp r2.xyz, r1, -r0.w, r2
    dp3_pp r0.x, -c7, r1
    dp3_pp r0.y, -c7, r2
    texld r18, r14, s2
    texld r17, r13, s2
    texld r16, r3, s2
    texld r3, r23, s2
    texld r15, r12, s2
    texld r14, r11, s2
    texld r13, r10, s2
    texld r12, r22, s2
    texld r11, r9, s2
    texld r10, r8, s2
    texld r9, r7, s2
    texld r8, r21, s2
    texld r7, r6, s2
    texld r6, r5, s2
    texld r5, r4, s2
    texld r4, r20, s2
    texld_pp r2, r24, s3
    texld_pp r0, r0, s4
    texld_pp r1, t0, s5
    dp4 r5.w, c2, r19
    add r3.y, -r18.x, r5.w
    add r3.z, -r17.x, r5.w
    mul r2.xy, r23, c9.z
    add r3.w, -r16.x, r5.w
    add r3.x, -r3.x, r5.w
    cmp_pp r3, -r3, c8.x, c8.w
    frc r17.xy, r2
    add_pp r2.xy, -r17, c8.x
    mul_pp r16.y, r17.y, r2.x
    mul_pp r16.z, r17.x, r2.y
    mul_pp r16.w, r17.y, r17.x
    mul_pp r16.x, r2.y, r2.x
    dp4_pp r3.x, r3, r16
    add r12.y, -r15.x, r5.w
    add r12.z, -r14.x, r5.w
    mul r2.xy, r22, c9.z
    add r12.w, -r13.x, r5.w
    add r12.x, -r12.x, r5.w
    cmp_pp r12, -r12, c8.x, c8.w
    frc r14.xy, r2
    add_pp r2.xy, -r14, c8.x
    mul_pp r13.y, r14.y, r2.x
    mul_pp r13.z, r14.x, r2.y
    mul_pp r13.w, r14.y, r14.x
    mul_pp r13.x, r2.y, r2.x
    dp4_pp r3.y, r12, r13
    add r8.y, -r11.x, r5.w
    add r8.z, -r10.x, r5.w
    mul r2.xy, r21, c9.z
    add r8.w, -r9.x, r5.w
    add r8.x, -r8.x, r5.w
    cmp_pp r8, -r8, c8.x, c8.w
    frc r2.xy, r2
    add_pp r10.xy, -r2, c8.x
    mul_pp r9.y, r2.y, r10.x
    mul_pp r9.z, r2.x, r10.y
    mul_pp r9.x, r10.y, r10.x
    mul_pp r9.w, r2.y, r2.x
    dp4_pp r3.z, r8, r9
    add r4.y, -r7.x, r5.w
    add r4.z, -r6.x, r5.w
    mul r2.xy, r20, c9.z
    add r4.w, -r5.x, r5.w
    add r4.x, -r4.x, r5.w
    cmp_pp r4, -r4, c8.x, c8.w
    frc r2.xy, r2
    add_pp r6.xy, -r2, c8.x
    mul_pp r5.y, r2.y, r6.x
    mul_pp r5.z, r2.x, r6.y
    mul_pp r5.x, r6.y, r6.x
    mul_pp r5.w, r2.y, r2.x
    dp4_pp r3.w, r4, r5
    dp4_pp r3.w, r3, c9.w
    mul_pp r2.w, r2.w, r3.w
    mul_pp r0, r0, c6
    mad_pp r0, r0, r2.w, r1
    mov_pp oC0, r0

// approximately 112 instruction slots used (21 texture, 91 arithmetic)
