//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /DUSE_SHADER3=1 /nologo /Tps_3_0 /Emain /Zpr /Fctest\p30_yuv2rgb.ps
//    yuv2rgb.ps
//
//
// Parameters:
//
//   sampler2D s_base;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   s_base       s1       1
//

    ps_3_0
    def c0, -0.869610012, 0.53075999, -1.07860005, 0
    def c1, 1.16406, -0.390625, 2.01561999, 1
    def c2, 1.59765005, -0.8125, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s1
    texld_pp r0, v0, s1
    mul_pp r1.x, r0.x, c1.x
    mad_pp r1.yz, r0.y, c1, r1.x
    mad_pp r0.xy, r0.z, c2, r1
    mov_pp r0.z, r1.z
    add_pp oC0.xyz, r0, c0
    mov_pp oC0.w, c1.w

// approximately 7 instruction slots used (1 texture, 6 arithmetic)
