//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /DUSE_SHADER3=1 /nologo /Tps_3_0 /Emain /Zpr /Fctest\p30_clouds.ps
//    clouds.ps
//
//
// Parameters:
//
//   sampler2D s_clouds0;
//   sampler2D s_clouds1;
//   sampler2D s_tonemap;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   s_clouds0    s0       1
//   s_clouds1    s1       1
//   s_tonemap    s2       1
//

    ps_3_0
    def c0, 0.5, 0, 0, 0
    dcl_color_pp v0
    dcl_texcoord_pp v1.xy
    dcl_texcoord1_pp v2.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    texld_pp r0, v1, s0
    texld_pp r1, v2, s1
    add_pp r0.xyz, r0, r1
    mul_pp r1.xyz, r0, v0
    texld_pp r0, c0.x, s2
    mul_pp oC0.xyz, r1, r0.x
    mov_pp oC0.w, v0.w

// approximately 7 instruction slots used (3 texture, 4 arithmetic)
