//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /DUSE_SHADER3=1 /nologo /Tps_3_0 /Emain /Zpr
//    /Fctest\p30_accum_sun_far.ps accum_sun_far.ps
//
//
// Parameters:
//
//   float4 Ldynamic_color;
//   float4 Ldynamic_dir;
//   row_major float4x4 m_shadow;
//   row_major float3x4 m_sunmask;
//   sampler2D s_accumulator;
//   sampler2D s_lmap;
//   sampler3D s_material;
//   sampler2D s_normal;
//   sampler2D s_position;
//   sampler2D s_smap;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   m_shadow       c0       4
//   m_sunmask      c4       2
//   Ldynamic_color c6       1
//   Ldynamic_dir   c7       1
//   s_smap         s0       1
//   s_position     s1       1
//   s_normal       s2       1
//   s_lmap         s3       1
//   s_material     s4       1
//   s_accumulator  s5       1
//

    ps_3_0
    def c8, 1, 0, -0.000244140625, 0.000244140625
    def c9, 2048, 0.00555555569, 0.333000004, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_volume s4
    dcl_2d s5
    texld r0, v0, s1
    mad r1, r0.xyzx, c8.xxxy, c8.yyyx
    dp4 r2.w, c3, r1
    rcp r4.z, r2.w
    dp4 r4.x, c0, r1
    dp4 r4.y, c1, r1
    mad r2.xy, r4, r4.z, c8.zwzw
    texld r2, r2, s0
    dp4 r4.w, c2, r1
    add r2.y, -r2.x, r4.w
    mad r3.xy, r4, r4.z, c8.wzzw
    texld r3, r3, s0
    add r2.z, r4.w, -r3.x
    mad r3.xy, r4, r4.z, c8.w
    mad r4.xy, r4, r4.z, c8.z
    texld r3, r3, s0
    add r2.w, r4.w, -r3.x
    texld r3, r4, s0
    mul r4.xy, r4, c9.x
    frc r5.xy, r4
    add r2.x, r4.w, -r3.x
    add_pp r4.xy, -r5, c8.x
    cmp_pp r2, -r2, c8.x, c8.y
    mul_pp r3.yz, r5.xyxw, r4.xxyw
    mul_pp r3.w, r5.y, r5.x
    mul_pp r3.x, r4.y, r4.x
    dp4_pp r2.w, r2, r3
    dp4 r2.x, c4, r1
    dp4 r2.y, c5, r1
    texld_pp r1, r2, s3
    mad_pp r1.x, r1.w, -r2.w, c9.z
    mul_sat r1.z, r0.z, c9.y
    mul r1.y, r1.z, r1.z
    dp3_pp r1.z, r0, r0
    mul r1.y, r1.x, r1.y
    rsq_pp r1.z, r1.z
    mad_pp r2.w, r1.w, r2.w, r1.y
    mad_pp r1.xyz, r0, -r1.z, -c7
    mov_pp r0.z, r0.w
    nrm_pp r2.xyz, r1
    texld_pp r1, v0, s2
    dp3_pp r0.y, r2, r1
    dp3_pp r0.x, -c7, r1
    texld_pp r0, r0, s4
    mul_pp r0, r0, c6
    texld_pp r1, v0, s5
    mad_pp oC0, r0, r2.w, r1

// approximately 49 instruction slots used (9 texture, 40 arithmetic)
