//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /DUSE_SHADER3=1 /nologo /Tps_3_0 /Emain /Zpr
//    /Fctest\p30_deffer_impl_flat.ps deffer_impl_flat.ps
//
//
// Parameters:
//
//   float4 L_material;
//   sampler2D s_base;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   L_material   c0       1
//   s_base       s0       1
//

    ps_3_0
    def c1, 0.0250000004, 1, 0, 0.00784313772
    dcl_texcoord v1.xy
    dcl_texcoord1 v2.xyz
    dcl_texcoord2_pp v3.xyz
    dcl_2d s0
    nrm_pp r0.xyz, v3
    mad_pp oC0.xyz, r0, c1.x, v2
    mov_pp oC1.xyz, r0
    mov_pp oC0.w, c0.w
    texld_pp r0, v1, s0
    mov_pp oC1.w, r0.w
    mad_pp oC2, r0.xyzx, c1.yyyz, c1.zzzw

// approximately 9 instruction slots used (1 texture, 8 arithmetic)
