//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /DUSE_SHADER3=1 /nologo /Tps_3_0 /Emain /Zpr /Fctest\p30_sky2.ps
//    sky2.ps
//
//
// Parameters:
//
//   samplerCUBE s_sky0;
//   samplerCUBE s_sky1;
//   sampler2D s_tonemap;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   s_sky0       s0       1
//   s_sky1       s1       1
//   s_tonemap    s2       1
//

    ps_3_0
    def c0, 0.5, 0, 0.333333343, 1
    dcl_color_pp v0
    dcl_texcoord_pp v1.xyz
    dcl_texcoord1_pp v2.xyz
    dcl_cube s0
    dcl_cube s1
    dcl_2d s2
    texld_pp r1, v1, s0
    texld_pp r0, v2, s1
    lrp_pp r2.xyz, v0.w, r0, r1
    mul_pp r1.xyz, r2, v0
    texld_pp r0, c0.x, s2
    add_pp r0.w, r0.x, r0.x
    mul_pp r0.xyz, r1, r0.w
    mov r0.w, c0.y
    mov_pp oC0, r0
    mul_pp oC1, r0, c0.zzzw

// approximately 11 instruction slots used (3 texture, 8 arithmetic)
