//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /DUSE_SHADER3=1 /nologo /Tps_3_0 /Emain /Zpr
//    /Fctest\p30_accum_sun_near.ps accum_sun_near.ps
//
//
// Parameters:
//
//   float4 Ldynamic_color;
//   float4 Ldynamic_dir;
//   row_major float4x4 m_shadow;
//   row_major float3x4 m_sunmask;
//   sampler2D s_accumulator;
//   sampler2D s_lmap;
//   sampler3D s_material;
//   sampler2D s_normal;
//   sampler2D s_position;
//   sampler2D s_smap;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   m_shadow       c0       4
//   m_sunmask      c4       2
//   Ldynamic_color c6       1
//   Ldynamic_dir   c7       1
//   s_position     s0       1
//   s_normal       s1       1
//   s_smap         s2       1
//   s_lmap         s3       1
//   s_material     s4       1
//   s_accumulator  s5       1
//

    ps_3_0
    def c8, 1, 0, -0.000537109387, -4.88281257e-005
    def c9, 2048, 4.88281257e-005, -0.000537109387, -4.88281257e-005
    def c10, 0.000537109387, -0.000537109387, 0.25, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_volume s4
    dcl_2d s5
    texld r0, v0, s0
    mad r1, r0.xyzx, c8.xxxy, c8.yyyx
    dp4 r2.w, c3, r1
    rcp r7.z, r2.w
    dp4 r7.x, c0, r1
    dp4 r7.y, c1, r1
    mad r2.xy, r7, r7.z, c8.zwzw
    texld r2, r2, s2
    dp4 r7.w, c2, r1
    add r2.y, -r2.x, r7.w
    mad r3.xy, r7, r7.z, c8.wzzw
    texld r3, r3, s2
    add r2.z, r7.w, -r3.x
    mad r3.xy, r7, r7.z, c8.w
    texld r3, r3, s2
    add r2.w, r7.w, -r3.x
    mad r4.xy, r7, r7.z, c8.z
    texld r3, r4, s2
    mul r4.xy, r4, c9.x
    frc r4.xy, r4
    add r2.x, r7.w, -r3.x
    add_pp r5.xy, -r4, c8.x
    cmp_pp r2, -r2, c8.x, c8.y
    mul_pp r3.yz, r4.xyxw, r5.xxyw
    mul_pp r3.x, r5.y, r5.x
    mul_pp r3.w, r4.y, r4.x
    dp4_pp r2.x, r2, r3
    mad r3.xy, r7, r7.z, c9.ywzw
    texld r3, r3, s2
    add r3.y, r7.w, -r3.x
    mad r4.xy, r7, r7.z, c10
    texld r4, r4, s2
    add r3.z, r7.w, -r4.x
    mad r4.xy, r7, r7.z, -c9.zyzw
    texld r4, r4, s2
    add r3.w, r7.w, -r4.x
    mad r5.xy, r7, r7.z, c9.yzzw
    texld r4, r5, s2
    mul r5.xy, r5, c9.x
    frc r5.xy, r5
    add r3.x, r7.w, -r4.x
    add_pp r6.xy, -r5, c8.x
    cmp_pp r3, -r3, c8.x, c8.y
    mul_pp r4.yz, r5.xyxw, r6.xxyw
    mul_pp r4.x, r6.y, r6.x
    mul_pp r4.w, r5.y, r5.x
    dp4_pp r2.y, r3, r4
    mad r3.xy, r7, r7.z, c10.yxzw
    texld r3, r3, s2
    add r3.y, r7.w, -r3.x
    mad r4.xy, r7, r7.z, c9.wyzw
    texld r4, r4, s2
    add r3.z, r7.w, -r4.x
    mad r4.xy, r7, r7.z, -c9.yzzw
    texld r4, r4, s2
    add r3.w, r7.w, -r4.x
    mad r5.xy, r7, r7.z, c9.zyzw
    texld r4, r5, s2
    mul r5.xy, r5, c9.x
    add r3.x, r7.w, -r4.x
    frc r4.xy, r5
    cmp_pp r5, -r3, c8.x, c8.y
    add_pp r3.xy, -r4, c8.x
    mul_pp r6.yz, r4.xyxw, r3.xxyw
    mul_pp r6.x, r3.y, r3.x
    mul_pp r6.w, r4.y, r4.x
    mad r3.xy, r7, r7.z, -c8.wzzw
    texld r3, r3, s2
    add r3.y, r7.w, -r3.x
    mad r4.xy, r7, r7.z, -c8.zwzw
    texld r4, r4, s2
    add r3.z, r7.w, -r4.x
    mad r4.xy, r7, r7.z, -c8.z
    mad r7.xy, r7, r7.z, -c8.w
    texld r4, r4, s2
    add r3.w, r7.w, -r4.x
    texld r4, r7, s2
    mul r7.xy, r7, c9.x
    frc r8.xy, r7
    add r3.x, r7.w, -r4.x
    add_pp r7.xy, -r8, c8.x
    cmp_pp r3, -r3, c8.x, c8.y
    mul_pp r4.yz, r8.xyxw, r7.xxyw
    mul_pp r4.w, r8.y, r8.x
    mul_pp r4.x, r7.y, r7.x
    dp4_pp r2.z, r5, r6
    dp4_pp r2.w, r3, r4
    dp4_pp r3.w, r2, c10.z
    dp4 r2.x, c4, r1
    dp4 r2.y, c5, r1
    texld_pp r2, r2, s3
    nrm_pp r2.xyz, r0
    texld_pp r1, v0, s1
    dp3_pp r0.z, r2, r1
    mul_pp r2.w, r3.w, r2.w
    add_pp r0.y, r0.z, r0.z
    mov_pp r0.z, r0.w
    mad_pp r2.xyz, r1, -r0.y, r2
    dp3_pp r0.x, -c7, r1
    dp3_pp r0.y, -c7, r2
    texld_pp r0, r0, s4
    mul_pp r0, r0, c6
    texld_pp r1, v0, s5
    mad_pp oC0, r0, r2.w, r1

// approximately 106 instruction slots used (21 texture, 85 arithmetic)
