# ServerBrowsing SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=sbctest

PROG_OBJS = \
	../sbctest.o\
	../../../hashtable.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsMemory.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../natneg/natneg.o\
	../../../natneg/NATify.o\
	../../sb_crypt.o\
	../../sb_queryengine.o\
	../../sb_server.o\
	../../sb_serverbrowsing.o\
	../../sb_serverlist.o\
	../../../qr2/qr2regkeys.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
