//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /nologo /Tps_2_0 /Emain /Zpr /Fctest\p20_accum_sun_far.ps
//    accum_sun_far.ps
//
//
// Parameters:
//
//   float4 Ldynamic_color;
//   float4 Ldynamic_dir;
//   row_major float4x4 m_shadow;
//   row_major float3x4 m_sunmask;
//   sampler2D s_accumulator;
//   sampler2D s_lmap;
//   sampler3D s_material;
//   sampler2D s_normal;
//   sampler2D s_position;
//   sampler2D s_smap;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   m_shadow       c0       4
//   m_sunmask      c4       2
//   Ldynamic_color c6       1
//   Ldynamic_dir   c7       1
//   s_smap         s0       1
//   s_position     s1       1
//   s_normal       s2       1
//   s_lmap         s3       1
//   s_material     s4       1
//   s_accumulator  s5       1
//

    ps_2_0
    def c8, 1, -0.000244140625, 0.000244140625, 0
    def c9, -0.000244140625, 0.000244140625, 2048, 0.00555555569
    def c10, 0.333000004, 0, 0, 0
    dcl t0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_volume s4
    dcl_2d s5
    texld r0, t0, s1
    texld_pp r1, t0, s2
    mov r3.w, c8.x
    mov r3.xyz, r0
    dp4 r1.w, c3, r3
    dp4 r0.x, c0, r3
    rcp r1.w, r1.w
    dp4 r0.y, c1, r3
    mad r7.xy, r0, r1.w, c9
    mad r6.xy, r0, r1.w, -c9
    mad r5.xy, r0, r1.w, c8.z
    mad r8.xy, r0, r1.w, c8.y
    dp4 r9.x, c4, r3
    dp3_pp r0.x, r3, r3
    dp4 r9.y, c5, r3
    rsq_pp r1.w, r0.x
    mad_pp r4.xyz, r3, -r1.w, -c7
    mov_pp r0.z, r0.w
    nrm_pp r2.xyz, r4
    dp3_pp r0.y, r2, r1
    dp3_pp r0.x, -c7, r1
    texld r7, r7, s0
    texld r6, r6, s0
    texld r5, r5, s0
    texld r4, r8, s0
    texld_pp r2, r9, s3
    texld_pp r0, r0, s4
    texld_pp r1, t0, s5
    dp4 r3.w, c2, r3
    add r4.y, -r7.x, r3.w
    add r4.z, -r6.x, r3.w
    mul r2.xy, r8, c9.z
    add r4.w, -r5.x, r3.w
    add r4.x, -r4.x, r3.w
    cmp_pp r4, -r4, c8.x, c8.w
    frc r2.xy, r2
    add_pp r3.xy, -r2, c8.x
    mul_pp r5.y, r2.y, r3.x
    mul_pp r5.z, r2.x, r3.y
    mul_pp r5.x, r3.y, r3.x
    mul_pp r5.w, r2.y, r2.x
    dp4_pp r3.w, r4, r5
    mad_pp r5.w, r2.w, -r3.w, c10.x
    mul_sat r4.w, r3.z, c9.w
    mul r4.w, r4.w, r4.w
    mul r4.w, r5.w, r4.w
    mad_pp r2.w, r2.w, r3.w, r4.w
    mul_pp r0, r0, c6
    mad_pp r0, r0, r2.w, r1
    mov_pp oC0, r0

// approximately 52 instruction slots used (9 texture, 43 arithmetic)
