//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.07.239.0000
//
//   fxc /nologo /Tps_2_0 /Emain /Zpr /Fctest\p20_deffer_impl_flat.ps
//    deffer_impl_flat.ps
//
//
// Parameters:
//
//   float4 L_material;
//   sampler2D s_base;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   L_material   c0       1
//   s_base       s0       1
//

    ps_2_0
    def c1, 0.0250000004, 0.00784313772, 0, 0
    dcl t0.xy
    dcl t1.xyz
    dcl_pp t2.xyz
    dcl_2d s0
    texld_pp r0, t0, s0
    nrm_pp r1.xyz, t2
    mov_pp r2.w, c0.w
    mad_pp r2.xyz, r1, c1.x, t1
    mov_pp oC0, r2
    mov_pp r1.w, r0.w
    mov_pp oC1, r1
    mov r0.w, c1.y
    mov_pp oC2, r0

// approximately 11 instruction slots used (1 texture, 10 arithmetic)
