#!/usr/bin/env python3
"""Freeze Vulkan device-test evidence and reject mismatched APK/build metadata."""
import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess

SCENARIOS = {
    "menu": {"game": None, "effects": []},
    "soc_day": {"game": "SoC", "effects": ["sun", "hud", "npc"]},
    "cs_rain": {"game": "CS", "effects": ["rain", "water", "hud"]},
    "cop_night": {"game": "CoP", "effects": ["local_lights", "particles", "hud"]},
}


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario", required=True, choices=SCENARIOS)
    parser.add_argument("--apk", required=True, type=pathlib.Path)
    parser.add_argument("--log", required=True, type=pathlib.Path)
    parser.add_argument("--frame", action="append", type=pathlib.Path, default=[])
    parser.add_argument("--device", required=True, help="Model, Android version, GPU and driver")
    parser.add_argument("--camera-demo", type=pathlib.Path, help="Recorded .xrdemo camera route")
    parser.add_argument("--level-save", type=pathlib.Path, help="Save that loads the tested level")
    parser.add_argument("--effects-config", type=pathlib.Path, help="Commands and weather/effects preset used")
    parser.add_argument("--build-commit", required=True, help="Full SHA from the exact native APK build")
    parser.add_argument("--build-manifest", required=True, type=pathlib.Path,
                        help="build-manifest.txt generated by build-apk-armv7.sh")
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    if len(args.build_commit) != 40 or any(c not in "0123456789abcdef" for c in args.build_commit):
        parser.error("--build-commit must be a full lower-case Git SHA")
    if SCENARIOS[args.scenario]["game"] and not all((args.camera_demo, args.level_save, args.effects_config)):
        parser.error("game scenarios require --camera-demo, --level-save and --effects-config")
    if not args.frame:
        parser.error("at least one --frame is required")
    for path in [args.apk, args.log, args.build_manifest, *args.frame,
                 *(p for p in (args.camera_demo, args.level_save, args.effects_config) if p)]:
        if not path.is_file():
            parser.error(f"missing evidence: {path}")
    build_metadata = dict(line.split("=", 1) for line in
                          args.build_manifest.read_text(encoding="utf-8").splitlines()
                          if "=" in line)
    if build_metadata.get("repo_commit") != args.build_commit:
        parser.error("build manifest repo_commit differs from --build-commit")
    if args.output.exists():
        parser.error(f"output already exists: {args.output}")
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    args.output.mkdir(parents=True)
    evidence = {}
    for label, paths in (("apk", [args.apk]), ("log", [args.log]),
                         ("build_manifest", [args.build_manifest]), ("frames", args.frame),
                         ("camera_demo", [args.camera_demo] if args.camera_demo else []),
                         ("level_save", [args.level_save] if args.level_save else []),
                         ("effects_config", [args.effects_config] if args.effects_config else [])):
        evidence[label] = []
        for index, path in enumerate(paths):
            target = args.output / f"{label}-{index}{path.suffix.lower()}"
            shutil.copyfile(path, target)
            evidence[label].append({"file": target.name, "sha256": sha256(target)})
    manifest = {"scenario": args.scenario, "fixture": SCENARIOS[args.scenario],
                "build_commit": args.build_commit, "capture_checkout": commit,
                "device": args.device, "evidence": evidence}
    (args.output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
