macro(add_dir DIRS)
  foreach(dir ${DIRS})
	message( "adding " ${dir} )
	include_directories  (${dir} )
	file( GLOB ${dir}__INCLUDES_H ${dir} *.h)
	file( GLOB ${dir}__INCLUDES_HPP ${dir} *.hpp)
	list( APPEND XRCORE__INCLUDES ${${dir}__INCLUDES_H} ${${dir}__INCLUDES_HPP} )	
	file( GLOB ${dir}__SOURCES ${dir} *.cpp) 
	list( APPEND XRCORE__SOURCES ${${dir}__SOURCES} )	
  endforeach()
endmacro()
