find_path(BUGTRAP_INCLUDE_DIR
    NAMES BugTrap.h
    PATH_SUFFIXES include
)

find_library(BUGTRAP_LIB
    NAMES BugTrap
)

find_file(BUGTRAP_DLL
    NAMES BugTrap.dll
    PATHS "${XRAY_SDK_BINARY_DIR}"
)

mark_as_advanced(
    BUGTRAP_INCLUDE_DIR
    BUGTRAP_LIB
    BUGTRAP_DLL
)

add_library(BugTrap SHARED IMPORTED GLOBAL)

set_target_properties(BugTrap PROPERTIES
    IMPORTED_LOCATION "${BUGTRAP_DLL}"
    IMPORTED_IMPLIB   "${BUGTRAP_LIB}"
    INTERFACE_INCLUDE_DIRECTORIES "${BUGTRAP_INCLUDE_DIR}"
)
