function(xray_gli_include_dir output)
    set(gli_include_dir "${CMAKE_SOURCE_DIR}/Externals/gli")
    if(ANDROID)
        set(gli_include_dir "${CMAKE_BINARY_DIR}/generated/android-gli")
        file(COPY "${CMAKE_SOURCE_DIR}/Externals/gli/gli" DESTINATION "${gli_include_dir}")
        set(loader "${gli_include_dir}/gli/core/load_dds.inl")
        file(READ "${loader}" source)
        set(unaligned "detail::dds_header const & Header(*reinterpret_cast<detail::dds_header const *>(Data + Offset));")
        set(aligned "detail::dds_header Header;\n\t\tstd::memcpy(&Header, Data + Offset, sizeof(Header));")
        string(FIND "${source}" "${unaligned}" offset)
        if(NOT offset EQUAL -1)
            string(REPLACE "${unaligned}" "${aligned}" source "${source}")
            file(WRITE "${loader}" "${source}")
        elseif(NOT source MATCHES "std::memcpy\\(&Header, Data \\+ Offset, sizeof\\(Header\\)\\)")
            message(FATAL_ERROR "Pinned GLI DDS loader changed; review the Android alignment overlay")
        endif()
    endif()
    set(${output} "${gli_include_dir}" PARENT_SCOPE)
endfunction()
