name: Mirror

on: [push, delete, workflow_dispatch]

jobs:
  to_bitbucket:
    if: github.repository == 'OpenXRay/xray-16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@bitbucket.org:OpenXRay/xray-16.git
          ssh_private_key: ${{ secrets.RABOTYAGA_BITBUCKET_PRIVATE_SSH_KEY }}
    
